### ISSUE TITLE
Migration tool is touching `refresh` calls that are not Riverpod related

### ISSUE THREAD

**Issue by chengyuhui** [rrousselGit/riverpod#1193]
**Describe the bug**
The migration tool is doing this in the code base:
![image](https://user-images.githubusercontent.com/1381736/154018516-fe3378a7-a16b-410f-9f27-2cfa04dd16ce.png)
where `currentMsgNoticesLoader` is a custom class that has a `refresh` method that is unrelated to Riverpod.

```
[REDACTED]/contact_page.dart: had error when visiting a method invocation currentMsgNoticesLoader.refresh()
Bad state: No element
#0      ListMixin.first (dart:collection/list.dart:99:22)
#1      RiverpodUnifiedSyntaxChangesMigrationSuggestor.visitMethodInvocation (package:riverpod_cli/src/migrate/unified_syntax.dart:866:64)
#2      MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7156:50)
#3      AwaitExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:874:17)
#4      GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:456:10)
#5      GeneralizingAstVisitor.visitCollectionElement (package:analyzer/dart/ast/visitor.dart:191:56)
#6      GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:273:42)
#7      GeneralizingAstVisitor.visitAwaitExpression (package:analyzer/dart/ast/visitor.dart:159:52)
#8      AwaitExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:870:50)
#9      ReturnStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:8550:18)
#10     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:456:10)
#11     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:528:40)
#12     GeneralizingAstVisitor.visitReturnStatement (package:analyzer/dart/ast/visitor.dart:500:52)
#13     ReturnStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:8546:50)
#14     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7581:20)
#15     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1056:17)
#16     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:456:10)
#17     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:528:40)
#18     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:165:32)
#19     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1052:50)
#20     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1011:12)
#21     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:456:10)
#22     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:330:46)
#23     GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:168:56)
#24     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1007:50)
#25     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7016:11)
#26     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:456:10)
#27     GeneralizingAstVisitor.visitAnnotatedNode (package:analyzer/dart/ast/visitor.dart:137:48)
#28     GeneralizingAstVisitor.visitDeclaration (package:analyzer/dart/ast/visitor.dart:235:44)
#29     GeneralizingAstVisitor.visitClassMember (package:analyzer/dart/ast/visitor.dart:186:44)
#30     GeneralizingAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:429:56)
#31     RiverpodUnifiedSyntaxChangesMigrationSuggestor.visitMethodDeclaration (package:riverpod_cli/src/migrate/unified_syntax.dart:799:11)
#32     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7007:50)
#33     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7581:20)
#34     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1530:13)
#35     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:456:10)
#36     GeneralizingAstVisitor.visitAnnotatedNode (package:analyzer/dart/ast/visitor.dart:137:48)
#37     GeneralizingAstVisitor.visitDeclaration (package:analyzer/dart/ast/visitor.dart:235:44)
#38     GeneralizingAstVisitor.visitCompilationUnitMember (package:analyzer/dart/ast/visitor.dart:205:7)
#39     GeneralizingAstVisitor.visitNamedCompilationUnitMember (package:analyzer/dart/ast/visitor.dart:440:7)
#40     GeneralizingAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:184:7)
#41     RiverpodUnifiedSyntaxChangesMigrationSuggestor.visitClassDeclaration (package:riverpod_cli/src/migrate/unified_syntax.dart:251:11)
#42     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1500:50)
#43     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7581:20)
#44     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2091:21)
#45     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:456:10)
#46     GeneralizingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:202:52)
#47     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2084:50)
#48     AstVisitingSuggestor.call (package:codemod/src/ast_visiting_suggestor.dart:79:10)
<asynchronous suspension>
```

**To Reproduce**

```dart
class ContactPage extends StatefulHookConsumerWidget {
  ContactPage({Key? key}) : super(key: key);

  @override
  _ContactPageState createState() => _ContactPageState();
}

class Loader {
  Future<void> refresh() {}
}

final currentMsgNoticesLoader = Loader();

class _ContactPageState extends ConsumerState<ContactPage> {
  Future<void> _refresh() async {
    return await currentMsgNoticesLoader.refresh();
  }
  // ...
}
```

**Expected behavior**
The migration tool should not touch this part of the code.

`Package riverpod_cli is currently active at version 1.0.3.`

**Comment by rrousselGit** [comment]
I'll close this. I have no plan to fix the remaining bugs for the migration tool as it's been quite a while now since the breaking change happened.
