### ISSUE TITLE
autoDispose.family fails when using both WidgetsFlutterBinding.ensureInitialized() and runZonedGuarded()

### ISSUE THREAD

**Issue by nailgilaziev** [rrousselGit/riverpod#1377]
`Unhandled Exception` occurs and autoDispose.family *future* provider stuck in `AsyncLoading` state when app uses `WidgetsFlutterBinding.ensureInitialized()` and `runZonedGuarded()` together.

**To Reproduce**

<details>
<summary>sample code</summary>

```dart
import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:collection/collection.dart';

void log(String msg, [Object? e]) {
  if (kDebugMode) {
    print('$msg${e == null ? '' : ': $e'}');
  }
}

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runZonedGuarded(guardedMain, (e, st) {
    log('Zone catch unhandled', e);
  });
}

void guardedMain() {
  runApp(ProviderScope(
    child: MaterialApp(
      debugShowCheckedModeBanner: false,
      home: MasterDetailScaffold(),
    ),
  ));
}

class Model {
  final int id;
  final String name;

  Model(this.id, this.name);
}

var fatal = true;

final listFutureProvider = FutureProvider((ref) async {
  log('listFutureProvider await pause');
  await Future.delayed(Duration(seconds: 1));
  log('listFutureProvider await complete');
  fatal = !fatal;
  if (fatal) {
    log('listFutureProvider will throw ex');
    throw 'some exception';
  }
  log('listFutureProvider return list');
  return [
    Model(1, 'one'),
    Model(2, 'two'),
    Model(3, 'three'),
  ];
});

late final itemFutureProvider =
    FutureProvider.autoDispose.family<Model?, int>((ref, id) async {
  final List<Model> list;
  try {
    log('* itemFutureProvider await future');
    list = await ref.watch(listFutureProvider.future);
    log('* itemFutureProvider await complete');
  } catch (e) {
    log('* itemFutureProvider await failed. rethrow');
    rethrow;
  }
  var firstOrNull = list.firstWhereOrNull((e) => e.id == id);
  log('itemFutureProvider return item: ${firstOrNull?.hashCode}');
  return firstOrNull;
});

final selectedIdProvider = StateProvider((ref) => 1);

class MasterDetailScaffold extends HookConsumerWidget {
  const MasterDetailScaffold({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Scaffold(
        appBar: AppBar(
          title: Text('refresh for ex'),
          actions: [
            IconButton(
                onPressed: () {
                  ref.refresh(listFutureProvider);
                },
                icon: Icon(Icons.refresh)),
          ],
        ),
        body: Row(
          children: const [
            Expanded(child: ListPanel()),
            VerticalDivider(),
            Expanded(child: ItemPanel()),
          ],
        ));
  }
}

class ListPanel extends HookConsumerWidget {
  const ListPanel({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final listAV = ref.watch(listFutureProvider);
    return Center(
      child: listAV.when(
        loading: () => CircularProgressIndicator(),
        error: (Object error, StackTrace? stackTrace) => Text('$error'),
        data: (List<Model> data) => ListView.builder(
          itemCount: data.length,
          itemBuilder: (BuildContext context, int index) {
            final d = data[index];
            return ListTile(
              title: Text(d.name),
              subtitle: Text(d.id.toString()),
              onTap: () {
                ref.read(selectedIdProvider.state).state = d.id;
              },
            );
          },
        ),
      ),
    );
  }
}

class ItemPanel extends HookConsumerWidget {
  const ItemPanel({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final id = ref.watch(selectedIdProvider);
    final itemAV = ref.watch(itemFutureProvider(id));
    return Center(
      child: itemAV.when(
        loading: () => CircularProgressIndicator(),
        error: (Object error, StackTrace? stackTrace) => Text('$error'),
        data: (Model? data) => Text('${data?.name}'),
      ),
    );
  }
}
```

</details>

Press refresh button and next will happen:
- Incorrect behaviour: 
`ListPanel` widget that watching `listFutureProvider` will rebuild yourself to `AsyncLoading` and then to  `AsyncError`. 
But `ItemPanel` that watching `itemFutureProvider` will rebuild yourself to `AsyncLoading`  and stuck in that state. 

- Unhandled exception in logs
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: problem ocurred
#0      remoteListFutureProvider.<anonymous closure> (package:vmngr/main.dart:71:5)
<asynchronous suspension>
#1      _FutureProviderElementMixin._listenFuture.<anonymous closure> (package:riverpod/src/future_provider.dart:95:11)
<asynchronous suspension>
```

**Expected behaviour**

If you don't  use `WidgetsFlutterBinding.ensureInitialized();` or  `runZonedGuarded(...)` in `main()`  everything works perfectly.
But when they are together there is a problem. Each individually does not lead to such a problem. 

<details>
<summary>version details</summary>

```
flutter_hooks: ^0.18.3
hooks_riverpod: ^1.0.3
```

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-x64,)
```

</details>

Normal behaviour. `WidgetsFlutterBinding.ensureInitialized();` line commented.

https://user-images.githubusercontent.com/2749021/165139265-1bab4ed0-9f25-4d77-a880-645282331ec6.mov

Bug. `WidgetsFlutterBinding.ensureInitialized();` and `  runZonedGuarded(...)` used simultaneously.

https://user-images.githubusercontent.com/2749021/165139184-7071f5cd-32af-4ff7-ba33-c2f736b6fedc.mov

**Comment by rrousselGit** [comment]
It's unclear to me what is happening.

Riverpod creates a completer for `listFutureProvider.future`, and when `listFutureProvider` throws, it does `completer.compleError`. But for unknown reason, `future.then(..., onError: )` is never invoked, and `await` never finishes.


So I'm tempted to say that this is a Dart bug. As I'm certain Riverpod correctly sends the error. I double checked that the `await ref.watch(listFutureProvider.future)` and the internal code that emits the error correctly point to the same `Completer`.

So besides a Dart bug, I can't think of a reason as to why this would happen.

**Comment by simplenotezy** [comment]
Turns out the way to set up crashalytics (which was done 1 year ago with runZoneGuarded) is no longer ‘the way’. The only reason we seemed to had 'runZoneGuarded' was to use FirebaseCrashalytics. According to the new documentation they no longer recommend using runZoneGuarded: https://firebase.google.com/docs/crashlytics/get-started?platform=flutter

**Comment by joachimbulow** [comment]
Resorting to handling errors using `FlutterError.onError` as opposed to `runZonedGuarded` resolved the issue for now.

**Comment by rrousselGit** [comment]
Indeed this appears to be an invalid usage of `ensureInitialized`
Nowadays, the given example prints a warning in the console:

```
The Flutter bindings were initialized in a different zone than is now being used. This will likely cause confusion and bugs as any zone-specific configuration will inconsistently use the configuration of the original binding initialization zone or this zone based on hard-to-predict factors such as which zone was active when a particular callback was set.
It is important to use the same zone when calling `ensureInitialized` on the binding as when calling `runApp` later.
To make this warning fatal, set BindingBase.debugZoneErrorsAreFatal to true before the bindings are initialized (i.e. as the first statement in `void main() { }`).
```

I'll therefore close this
