### ISSUE TITLE
 Invalid argument(s): Missing canonical name for Reference to Criteria

### ISSUE THREAD

**Issue by zubyf09** [rrousselGit/riverpod#1425]
I am using the flutter_riverpod plugin. For Navigation use the beamer plugin. beamer: ^1.4.1+1.
It works fine on Android/IOS simulators.  But when I run the release build command. 'flutter build apk --release'

it's through's following exception. ***Invalid argument(s): Missing canonical name for Reference to Criteria ***

Code Sample.

`runApp(
  UncontrolledProviderScope(
    container: ProviderContainer(),
    child: MaterialApp.router(
      routeInformationParser: createBeamerParser(),
      routerDelegate: createBeamerDelegate(),
      builder: (BuildContext context, Widget? child) {
        return Example();
      },
    ),
  ),
)`

An exception I got after the release command.

[+11003 ms] [+12239 ms] Unhandled exception:
[        ]             Invalid argument(s): Missing canonical name for Reference to Criteria
[        ]             #0      BinaryPrinter.writeNonNullReference (package:kernel/binary/ast_to_binary.dart:941:9)
[        ]             #1      BinaryPrinter.visitInterfaceType (package:kernel/binary/ast_to_binary.dart:2346:7)
[        ]             #2      InterfaceType.accept (package:kernel/ast.dart:11439:42)
[        ]             #3      BinaryPrinter.writeDartType (package:kernel/binary/ast_to_binary.dart:309:10)
[        ]             #4      BinaryPrinter.writeConstantTableEntry (package:kernel/binary/ast_to_binary.dart:246:7)
[        ]             #5      BinaryPrinter.writeConstantTable (package:kernel/binary/ast_to_binary.dart:198:7)
[        ]             #6      BinaryPrinter.writeComponentFile.<anonymous closure> (package:kernel/binary/ast_to_binary.dart:598:7)
[        ]             #7      Timeline.timeSync (dart:developer/timeline.dart:160:22)
[        ]             #8      BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:577:14)
[        ]             #9      FrontendCompiler.writeDillFile (file:///opt/s/w/ir/cache/builder/sdk/pkg/frontend_server/lib/frontend_server.dart:742:13)
[   +2 ms]             #10     FrontendCompiler.compile (file:///opt/s/w/ir/cache/builder/sdk/pkg/frontend_server/lib/frontend_server.dart:613:13)
[        ]             <asynchronous suspension>
[        ]             #11     starter (file:///opt/s/w/ir/cache/builder/sdk/pkg/frontend_server/lib/frontend_server.dart:1447:12)
[        ]             <asynchronous suspension>
[        ]             #12     main (file:///opt/s/w/ir/cache/builder/sdk/pkg/frontend_server/bin/frontend_server_starter.dart:10:14)
[        ]             <asynchronous suspension>

**Comment by zubyf09** [comment]
@rrousselGit  If I removed **UncontrolledProviderScope**, or  **ProviderScope** it allows me to generate a release build

**Comment by zubyf09** [comment]
@rrousselGit  thanks for your quick response. The issue was with my model. I was using the state model

`
class ServiceDetailsState {
  bool isLoading;
  ServicesModel? servicesModel;
 
  ServiceDetailsState({
    this.servicesModel,
    this.isLoading = false,
  });

  ServiceDetailsState copyWith({
    ServicesModel? servicesModel,
    bool? isLoading,
  }) =>
      ServiceDetailsState(
        servicesModel: servicesModel ?? this.servicesModel,
        isLoading: isLoading ?? this.isLoading,
      );

  factory ServiceDetailsState.empty() => ServiceDetailsState(
    servicesModel: ServicesModel.empty(),
    isLoading: false,
  );
}`
In my factory method I was assigning   **servicesModel: ServicesModel.empty(),** I changed this parameter like this servicesModel: ServicesModel(),  And it allows me to build a release app.
