### ISSUE TITLE
`This UncontrolledProviderScope widget cannot be marked as needing to build` occurs

### ISSUE THREAD

**Issue by motucraft** [rrousselGit/riverpod#1438]
**Describe the bug**
`This UncontrolledProviderScope widget cannot be marked as needing to build` occurs. Am I using it incorrectly?

<details>
<summary>error log</summary>

```
======== Exception caught by widgets library =======================================================
The following StateNotifierListenerError was thrown building LayoutBuilder:
At least listener of the StateNotifier Instance of 'StateController<ScreenSize>' threw an exception
when the notifier tried to update its state.

The exceptions thrown are:

setState() or markNeedsBuild() called during build.
This UncontrolledProviderScope widget cannot be marked as needing to build because the framework is already in the process of building widgets. A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was:
  UncontrolledProviderScope
The widget which was currently being built when the offending call was made was:
  LayoutBuilder
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_
packages/flutter/src/widgets/framework.dart 4476:11                           <fn>
packages/flutter/src/widgets/framework.dart 4490:14                           markNeedsBuild
packages/flutter_riverpod/src/framework.dart 287:5                            [_debugCanModifyProviders]
packages/riverpod/src/framework/provider_base.dart 513:42                     <fn>
packages/riverpod/src/framework/provider_base.dart 337:7                      setState
packages/state_notifier/state_notifier.dart 225:23                            set state
packages/riverpod/src/state_provider.dart 21:31                               set state
packages/riverpod/src/state_provider.dart 37:39                               update
packages/riverpod_problem/main.dart 40:39                                     <fn>
packages/flutter/src/widgets/layout_builder.dart 119:70                       layoutCallback
packages/flutter/src/widgets/framework.dart 2597:19                           buildScope
packages/flutter/src/widgets/layout_builder.dart 153:5                        [_layout]
packages/flutter/src/rendering/object.dart 2025:59                            <fn>
packages/flutter/src/rendering/object.dart 918:15                             [_enableMutationsToDirtySubtrees]
packages/flutter/src/rendering/object.dart 2025:7                             invokeLayoutCallback
packages/flutter/src/widgets/layout_builder.dart 227:7                        rebuildIfNecessary
packages/flutter/src/widgets/layout_builder.dart 316:5                        performLayout
packages/flutter/src/rendering/object.dart 1915:7                             layout
packages/flutter/src/rendering/proxy_box.dart 116:7                           performLayout
packages/flutter/src/rendering/object.dart 1915:7                             layout
packages/flutter/src/rendering/proxy_box.dart 116:7                           performLayout
packages/flutter/src/rendering/object.dart 1915:7                             layout
packages/flutter/src/rendering/proxy_box.dart 116:7                           performLayout
packages/flutter/src/rendering/object.dart 1915:7                             layout
packages/flutter/src/rendering/layout_helper.dart 56:10                       layoutChild
packages/flutter/src/rendering/stack.dart 552:43                              [_computeSize]
packages/flutter/src/rendering/stack.dart 579:12                              performLayout
packages/flutter/src/rendering/object.dart 1915:7                             layout
packages/flutter/src/rendering/proxy_box.dart 116:7                           performLayout
packages/flutter/src/rendering/object.dart 1915:7                             layout
packages/flutter/src/rendering/proxy_box.dart 116:7                           performLayout
packages/flutter/src/rendering/object.dart 1915:7                             layout
packages/flutter/src/rendering/proxy_box.dart 116:7                           performLayout
packages/flutter/src/rendering/object.dart 1915:7                             layout
packages/flutter/src/rendering/proxy_box.dart 116:7                           performLayout
packages/flutter/src/rendering/object.dart 1915:7                             layout
packages/flutter/src/rendering/proxy_box.dart 116:7                           performLayout
packages/flutter/src/rendering/object.dart 1915:7                             layout
packages/flutter/src/rendering/proxy_box.dart 116:7                           performLayout
packages/flutter/src/rendering/object.dart 1915:7                             layout
packages/flutter/src/rendering/proxy_box.dart 116:7                           performLayout
packages/flutter/src/rendering/proxy_box.dart 3462:13                         performLayout
packages/flutter/src/rendering/object.dart 1915:7                             layout
packages/flutter/src/rendering/proxy_box.dart 116:7                           performLayout
packages/flutter/src/rendering/object.dart 1915:7                             layout
packages/flutter/src/widgets/overlay.dart 749:14                              performLayout
packages/flutter/src/rendering/object.dart 1915:7                             layout
packages/flutter/src/rendering/proxy_box.dart 116:7                           performLayout
packages/flutter/src/rendering/object.dart 1915:7                             layout
packages/flutter/src/rendering/proxy_box.dart 116:7                           performLayout
packages/flutter/src/rendering/object.dart 1915:7                             layout
packages/flutter/src/rendering/proxy_box.dart 116:7                           performLayout
packages/flutter/src/rendering/object.dart 1915:7                             layout
packages/flutter/src/rendering/proxy_box.dart 116:7                           performLayout
packages/flutter/src/rendering/object.dart 1915:7                             layout
packages/flutter/src/rendering/proxy_box.dart 116:7                           performLayout
packages/flutter/src/rendering/object.dart 1915:7                             layout
packages/flutter/src/rendering/proxy_box.dart 116:7                           performLayout
packages/flutter/src/rendering/object.dart 1915:7                             layout
packages/flutter/src/rendering/proxy_box.dart 116:7                           performLayout
packages/flutter/src/rendering/object.dart 1915:7                             layout
packages/flutter/src/rendering/view.dart 165:7                                performLayout
packages/flutter/src/rendering/object.dart 1757:7                             [_layoutWithoutResize]
packages/flutter/src/rendering/object.dart 887:17                             flushLayout
packages/flutter/src/rendering/binding.dart 504:19                            drawFrame
packages/flutter/src/widgets/binding.dart 892:13                              drawFrame
packages/flutter/src/rendering/binding.dart 370:5                             [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1146:15                           [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1083:9                            handleDrawFrame
packages/flutter/src/scheduler/binding.dart 997:5                             [_handleDrawFrame]
lib/_engine/engine/platform_dispatcher.dart 1090:13                           invoke
lib/_engine/engine/platform_dispatcher.dart 160:5                             invokeOnDrawFrame
lib/_engine/engine/initialization.dart 194:45                                 <fn>

The relevant error-causing widget was: 
  LayoutBuilder LayoutBuilder:file:///Users/osaki/github/flutter/riverpod_problem/lib/main.dart:36:12
When the exception was thrown, this was the stack: 
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_
packages/state_notifier/state_notifier.dart 238:7                             set state
packages/riverpod/src/state_provider.dart 21:31                               set state
packages/riverpod/src/state_provider.dart 37:39                               update
packages/riverpod_problem/main.dart 40:39                                     <fn>
packages/flutter/src/widgets/layout_builder.dart 119:70                       layoutCallback
packages/flutter/src/widgets/framework.dart 2597:19                           buildScope
packages/flutter/src/widgets/layout_builder.dart 153:5                        [_layout]
packages/flutter/src/rendering/object.dart 2025:59                            <fn>
packages/flutter/src/rendering/object.dart 918:15                             [_enableMutationsToDirtySubtrees]
packages/flutter/src/rendering/object.dart 2025:7                             invokeLayoutCallback
packages/flutter/src/widgets/layout_builder.dart 227:7                        rebuildIfNecessary
packages/flutter/src/widgets/layout_builder.dart 316:5                        performLayout
packages/flutter/src/rendering/object.dart 1915:7                             layout
packages/flutter/src/rendering/proxy_box.dart 116:7                           performLayout
packages/flutter/src/rendering/object.dart 1915:7                             layout
packages/flutter/src/rendering/proxy_box.dart 116:7                           performLayout
packages/flutter/src/rendering/object.dart 1915:7                             layout
packages/flutter/src/rendering/proxy_box.dart 116:7                           performLayout
packages/flutter/src/rendering/object.dart 1915:7                             layout
packages/flutter/src/rendering/layout_helper.dart 56:10                       layoutChild
packages/flutter/src/rendering/stack.dart 552:43                              [_computeSize]
packages/flutter/src/rendering/stack.dart 579:12                              performLayout
packages/flutter/src/rendering/object.dart 1915:7                             layout
packages/flutter/src/rendering/proxy_box.dart 116:7                           performLayout
packages/flutter/src/rendering/object.dart 1915:7                             layout
packages/flutter/src/rendering/proxy_box.dart 116:7                           performLayout
packages/flutter/src/rendering/object.dart 1915:7                             layout
packages/flutter/src/rendering/proxy_box.dart 116:7                           performLayout
packages/flutter/src/rendering/object.dart 1915:7                             layout
packages/flutter/src/rendering/proxy_box.dart 116:7                           performLayout
packages/flutter/src/rendering/object.dart 1915:7                             layout
packages/flutter/src/rendering/proxy_box.dart 116:7                           performLayout
packages/flutter/src/rendering/object.dart 1915:7                             layout
packages/flutter/src/rendering/proxy_box.dart 116:7                           performLayout
packages/flutter/src/rendering/object.dart 1915:7                             layout
packages/flutter/src/rendering/proxy_box.dart 116:7                           performLayout
packages/flutter/src/rendering/proxy_box.dart 3462:13                         performLayout
packages/flutter/src/rendering/object.dart 1915:7                             layout
packages/flutter/src/rendering/proxy_box.dart 116:7                           performLayout
packages/flutter/src/rendering/object.dart 1915:7                             layout
packages/flutter/src/widgets/overlay.dart 749:14                              performLayout
packages/flutter/src/rendering/object.dart 1915:7                             layout
packages/flutter/src/rendering/proxy_box.dart 116:7                           performLayout
packages/flutter/src/rendering/object.dart 1915:7                             layout
packages/flutter/src/rendering/proxy_box.dart 116:7                           performLayout
packages/flutter/src/rendering/object.dart 1915:7                             layout
packages/flutter/src/rendering/proxy_box.dart 116:7                           performLayout
packages/flutter/src/rendering/object.dart 1915:7                             layout
packages/flutter/src/rendering/proxy_box.dart 116:7                           performLayout
packages/flutter/src/rendering/object.dart 1915:7                             layout
packages/flutter/src/rendering/proxy_box.dart 116:7                           performLayout
packages/flutter/src/rendering/object.dart 1915:7                             layout
packages/flutter/src/rendering/proxy_box.dart 116:7                           performLayout
packages/flutter/src/rendering/object.dart 1915:7                             layout
packages/flutter/src/rendering/proxy_box.dart 116:7                           performLayout
packages/flutter/src/rendering/object.dart 1915:7                             layout
packages/flutter/src/rendering/view.dart 165:7                                performLayout
packages/flutter/src/rendering/object.dart 1757:7                             [_layoutWithoutResize]
packages/flutter/src/rendering/object.dart 887:17                             flushLayout
packages/flutter/src/rendering/binding.dart 504:19                            drawFrame
packages/flutter/src/widgets/binding.dart 892:13                              drawFrame
packages/flutter/src/rendering/binding.dart 370:5                             [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1146:15                           [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1083:9                            handleDrawFrame
packages/flutter/src/scheduler/binding.dart 997:5                             [_handleDrawFrame]
lib/_engine/engine/platform_dispatcher.dart 1090:13                           invoke
lib/_engine/engine/platform_dispatcher.dart 160:5                             invokeOnDrawFrame
lib/_engine/engine/initialization.dart 194:45                                 <fn>
====================================================================================================
Error: setState() or markNeedsBuild() called during build.
This UncontrolledProviderScope widget cannot be marked as needing to build because the framework is already in the process of building widgets. A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was:
  UncontrolledProviderScope
The widget which was currently being built when the offending call was made was:
  LayoutBuilder
    at Object.throw_ [as throw] (http://localhost:64753/dart_sdk.js:5080:11)
    at http://localhost:64753/packages/flutter/src/widgets/title.dart.lib.js:21372:23
    at framework$0._UncontrolledProviderScopeElement.new.markNeedsBuild (http://localhost:64753/packages/flutter/src/widgets/title.dart.lib.js:21380:26)
    at [_debugCanModifyProviders] (http://localhost:64753/packages/flutter_riverpod/src/framework.dart.lib.js:303:12)
    at http://localhost:64753/packages/riverpod/src/state_provider.dart.lib.js:826:31
    at [_notifyListeners] (http://localhost:64753/packages/riverpod/src/state_provider.dart.lib.js:828:28)
    at StateProviderElement.new.setState (http://localhost:64753/packages/riverpod/src/state_provider.dart.lib.js:704:33)
    at set state (http://localhost:64753/packages/state_notifier/state_notifier.dart.lib.js:165:43)
    at set state [as state] (http://localhost:64753/packages/riverpod/src/state_provider.dart.lib.js:230:28)
    at StateController.new.update (http://localhost:64753/packages/riverpod/src/state_provider.dart.lib.js:234:27)
    at http://localhost:64753/packages/riverpod_problem/main.dart.lib.js:509:90
    at layoutCallback (http://localhost:64753/packages/flutter/src/widgets/layout_builder.dart.lib.js:132:167)
    at framework.BuildOwner.new.buildScope (http://localhost:64753/packages/flutter/src/widgets/title.dart.lib.js:53359:13)
    at [_layout] (http://localhost:64753/packages/flutter/src/widgets/layout_builder.dart.lib.js:164:36)
    at http://localhost:64753/packages/flutter/src/rendering/layer.dart.lib.js:3313:11
    at [_enableMutationsToDirtySubtrees] (http://localhost:64753/packages/flutter/src/rendering/layer.dart.lib.js:6230:9)
    at layout_builder._RenderLayoutBuilder.new.invokeLayoutCallback (http://localhost:64753/packages/flutter/src/rendering/layer.dart.lib.js:3312:68)
    at layout_builder._RenderLayoutBuilder.new.rebuildIfNecessary (http://localhost:64753/packages/flutter/src/widgets/layout_builder.dart.lib.js:253:16)
    at layout_builder._RenderLayoutBuilder.new.performLayout (http://localhost:64753/packages/flutter/src/widgets/layout_builder.dart.lib.js:355:12)
    at layout_builder._RenderLayoutBuilder.new.layout (http://localhost:64753/packages/flutter/src/rendering/layer.dart.lib.js:3277:14)
    at proxy_box.RenderSemanticsAnnotations.new.performLayout (http://localhost:64753/packages/flutter/src/rendering/proxy_box.dart.lib.js:426:38)
    at proxy_box.RenderSemanticsAnnotations.new.layout (http://localhost:64753/packages/flutter/src/rendering/layer.dart.lib.js:3277:14)
    at proxy_box.RenderRepaintBoundary.new.performLayout (http://localhost:64753/packages/flutter/src/rendering/proxy_box.dart.lib.js:426:38)
    at proxy_box.RenderRepaintBoundary.new.layout (http://localhost:64753/packages/flutter/src/rendering/layer.dart.lib.js:3277:14)
    at proxy_box.RenderIgnorePointer.new.performLayout (http://localhost:64753/packages/flutter/src/rendering/proxy_box.dart.lib.js:426:38)
    at proxy_box.RenderIgnorePointer.new.layout (http://localhost:64753/packages/flutter/src/rendering/layer.dart.lib.js:3277:14)
    at layoutChild (http://localhost:64753/packages/flutter/src/rendering/layout_helper.dart.lib.js:22:13)
    at [_computeSize] (http://localhost:64753/packages/flutter/src/rendering/stack.dart.lib.js:555:27)
    at stack.RenderStack.new.performLayout (http://localhost:64753/packages/flutter/src/rendering/stack.dart.lib.js:575:37)
    at stack.RenderStack.new.layout (http://localhost:64753/packages/flutter/src/rendering/layer.dart.lib.js:3277:14)
    at proxy_box.RenderDecoratedBox.new.performLayout (http://localhost:64753/packages/flutter/src/rendering/proxy_box.dart.lib.js:426:38)
    at proxy_box.RenderDecoratedBox.new.layout (http://localhost:64753/packages/flutter/src/rendering/layer.dart.lib.js:3277:14)
    at proxy_box.RenderFractionalTranslation.new.performLayout (http://localhost:64753/packages/flutter/src/rendering/proxy_box.dart.lib.js:426:38)
    at proxy_box.RenderFractionalTranslation.new.layout (http://localhost:64753/packages/flutter/src/rendering/layer.dart.lib.js:3277:14)
    at proxy_box.RenderFractionalTranslation.new.performLayout (http://localhost:64753/packages/flutter/src/rendering/proxy_box.dart.lib.js:426:38)
    at proxy_box.RenderFractionalTranslation.new.layout (http://localhost:64753/packages/flutter/src/rendering/layer.dart.lib.js:3277:14)
    at proxy_box.RenderRepaintBoundary.new.performLayout (http://localhost:64753/packages/flutter/src/rendering/proxy_box.dart.lib.js:426:38)
    at proxy_box.RenderRepaintBoundary.new.layout (http://localhost:64753/packages/flutter/src/rendering/layer.dart.lib.js:3277:14)
    at routes._RenderFocusTrap.new.performLayout (http://localhost:64753/packages/flutter/src/rendering/proxy_box.dart.lib.js:426:38)
    at routes._RenderFocusTrap.new.layout (http://localhost:64753/packages/flutter/src/rendering/layer.dart.lib.js:3277:14)
    at proxy_box.RenderSemanticsAnnotations.new.performLayout (http://localhost:64753/packages/flutter/src/rendering/proxy_box.dart.lib.js:426:38)
    at proxy_box.RenderSemanticsAnnotations.new.layout (http://localhost:64753/packages/flutter/src/rendering/layer.dart.lib.js:3277:14)
    at proxy_box.RenderOffstage.new.performLayout (http://localhost:64753/packages/flutter/src/rendering/proxy_box.dart.lib.js:426:38)
    at proxy_box.RenderOffstage.new.performLayout (http://localhost:64753/packages/flutter/src/rendering/proxy_box.dart.lib.js:3612:15)
    at proxy_box.RenderOffstage.new.layout (http://localhost:64753/packages/flutter/src/rendering/layer.dart.lib.js:3277:14)
    at proxy_box.RenderSemanticsAnnotations.new.performLayout (http://localhost:64753/packages/flutter/src/rendering/proxy_box.dart.lib.js:426:38)
    at proxy_box.RenderSemanticsAnnotations.new.layout (http://localhost:64753/packages/flutter/src/rendering/layer.dart.lib.js:3277:14)
    at overlay$._RenderTheatre.new.performLayout (http://localhost:64753/packages/flutter/src/widgets/title.dart.lib.js:26876:17)
    at overlay$._RenderTheatre.new.layout (http://localhost:64753/packages/flutter/src/rendering/layer.dart.lib.js:3277:14)
    at proxy_box.RenderSemanticsAnnotations.new.performLayout (http://localhost:64753/packages/flutter/src/rendering/proxy_box.dart.lib.js:426:38)
    at proxy_box.RenderSemanticsAnnotations.new.layout (http://localhost:64753/packages/flutter/src/rendering/layer.dart.lib.js:3277:14)
    at proxy_box.RenderAbsorbPointer.new.performLayout (http://localhost:64753/packages/flutter/src/rendering/proxy_box.dart.lib.js:426:38)
    at proxy_box.RenderAbsorbPointer.new.layout (http://localhost:64753/packages/flutter/src/rendering/layer.dart.lib.js:3277:14)
    at proxy_box.RenderPointerListener.new.performLayout (http://localhost:64753/packages/flutter/src/rendering/proxy_box.dart.lib.js:426:38)
    at proxy_box.RenderPointerListener.new.layout (http://localhost:64753/packages/flutter/src/rendering/layer.dart.lib.js:3277:14)
    at proxy_box.RenderSemanticsAnnotations.new.performLayout (http://localhost:64753/packages/flutter/src/rendering/proxy_box.dart.lib.js:426:38)
    at proxy_box.RenderSemanticsAnnotations.new.layout (http://localhost:64753/packages/flutter/src/rendering/layer.dart.lib.js:3277:14)
    at proxy_box.RenderSemanticsAnnotations.new.performLayout (http://localhost:64753/packages/flutter/src/rendering/proxy_box.dart.lib.js:426:38)
    at proxy_box.RenderSemanticsAnnotations.new.layout (http://localhost:64753/packages/flutter/src/rendering/layer.dart.lib.js:3277:14)
    at proxy_box.RenderSemanticsAnnotations.new.performLayout (http://localhost:64753/packages/flutter/src/rendering/proxy_box.dart.lib.js:426:38)
    at proxy_box.RenderSemanticsAnnotations.new.layout (http://localhost:64753/packages/flutter/src/rendering/layer.dart.lib.js:3277:14)
    at proxy_box.RenderSemanticsAnnotations.new.performLayout (http://localhost:64753/packages/flutter/src/rendering/proxy_box.dart.lib.js:426:38)
    at proxy_box.RenderSemanticsAnnotations.new.layout (http://localhost:64753/packages/flutter/src/rendering/layer.dart.lib.js:3277:14)
    at view.RenderView.new.performLayout (http://localhost:64753/packages/flutter/src/rendering/layer.dart.lib.js:4734:58)
    at [_layoutWithoutResize] (http://localhost:64753/packages/flutter/src/rendering/layer.dart.lib.js:3157:14)
    at object$.PipelineOwner.new.flushLayout (http://localhost:64753/packages/flutter/src/rendering/layer.dart.lib.js:6208:96)
    at binding$5.WidgetsFlutterBinding.new.drawFrame (http://localhost:64753/packages/flutter/src/rendering/layer.dart.lib.js:5507:26)
    at binding$5.WidgetsFlutterBinding.new.drawFrame (http://localhost:64753/packages/flutter/src/widgets/title.dart.lib.js:56093:15)
    at [_handlePersistentFrameCallback] (http://localhost:64753/packages/flutter/src/rendering/layer.dart.lib.js:5472:12)
    at [_invokeFrameCallback] (http://localhost:64753/packages/flutter/src/scheduler/binding.dart.lib.js:736:9)
    at binding$5.WidgetsFlutterBinding.new.handleDrawFrame (http://localhost:64753/packages/flutter/src/scheduler/binding.dart.lib.js:707:37)
    at [_handleDrawFrame] (http://localhost:64753/packages/flutter/src/scheduler/binding.dart.lib.js:660:12)
    at Object.invoke (http://localhost:64753/dart_sdk.js:191736:7)
    at _engine.EnginePlatformDispatcher.__.invokeOnDrawFrame (http://localhost:64753/dart_sdk.js:171933:15)
    at http://localhost:64753/dart_sdk.js:191477:57
```
</details>

**To Reproduce**
`flutter run -d chrome` and resize as follow:

![riverpod](https://user-images.githubusercontent.com/35750184/171563121-a723ee61-4cfa-4182-a0f8-806a1d4174f7.gif)

<details>
<summary>Full main.dart code</summary>

```dart
import 'package:flutter/material.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';

final screenSizeProvider = StateProvider((ref) => ScreenSize.small);

void main() => runApp(const ProviderScope(child: MyTodoApp()));

class BreakPointWidth {
  static const double smallToMid = 600;
  static const double midToLarge = 800;
}

enum ScreenSize {
  small,
  large,
}

class MyTodoApp extends StatelessWidget {
  const MyTodoApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData.dark(),
      home: const HomeScreen(),
    );
  }
}

class HomeScreen extends ConsumerWidget {
  const HomeScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return LayoutBuilder(
        builder: (BuildContext context, BoxConstraints constraints) {
      if (constraints.maxWidth >= BreakPointWidth.midToLarge) {
        ref
            .watch(screenSizeProvider.notifier)
            .update((state) => ScreenSize.large);
        return Row(
          children: const [
            Expanded(
              flex: 3,
              child: SideMenuPage(),
            ),
            Expanded(
              flex: 4,
              child: TaskListPage(),
            ),
          ],
        );
      } else {
        ref
            .watch(screenSizeProvider.notifier)
            .update((state) => ScreenSize.small);
        return Row(
          children: const [
            Expanded(
              flex: 1,
              child: TaskListPage(),
            ),
          ],
        );
      }
    });
  }
}

class SideMenuPage extends StatelessWidget {
  const SideMenuPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      backgroundColor: Color(0xFF1b1b1b),
    );
  }
}

class TaskListPage extends StatelessWidget {
  const TaskListPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Consumer(
      builder: (context, ref, child) {
        final screenSize = ref.watch(screenSizeProvider);

        return Scaffold(
          backgroundColor: const Color(0xFF212121),
          floatingActionButton: (screenSize == ScreenSize.large)
              ? null
              : FloatingActionButton(
                  onPressed: () => _addNewTask(context),
                  child: const Icon(Icons.add),
                ),
        );
      },
    );
  }

  _addNewTask(BuildContext context) {}
}
```
</details>

Reproduced on these version:

- hooks_riverpod: `1.0.4`
- flutter: `3.0.1`

**Expected behavior**

Works normally without errors.

**Comment by msarkrish** [comment]
@motucraft I think you have to use ref.read instead of ref.watch you are updating the value of provider so read is enough. I think using watch is here causes issue.

**Comment by motucraft** [comment]
@msarkrish Thank you. Simply changing to ‘read' does not seem to work.

**Comment by motucraft** [comment]
@rrousselGit 
> You'll need to find a different solution to do that

Thank you. I will think about it.
