### ISSUE TITLE
Null check operator used on a null value happened in ProviderContainer.updateOverrides

### ISSUE THREAD

**Issue by reedom** [rrousselGit/riverpod#1519]
**Describe the bug**
hooks_riverpod: 1.0.4
flutter_riverpod: 1.0.4
riverpod: 1.0.3
flutter_hooks: 0.18.5+1

`Null check operator used on a null value` happened in `ProviderContainer.updateOverrides`
after I've added `ProviderScope(overrides: […])` fragment to our code.

```dart
    for (final override in overrides) {
        …
        // _stateReaders[origin] cannot be null for overridden providers.
        final reader = _stateReaders[override._origin]!;
```

**To Reproduce**

steps:
1. open modal x2
2. close the last one

Minimum elements to reproduce would be:
- modal caller and callee do `ref.watch(provider)` and the callee changes the value after closing the modal.
- by condition, it switches whether to wrap or not with `ProviderScope(overrides: […])`.

(edit)
- the provider has `autoDispose` mark.

```dart
import 'package:flutter/material.dart';
import 'package:flutter_hooks/flutter_hooks.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';

void main() => runApp(const ProviderScope(child: MyApp()));

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Flutter Demo',
        home: Scaffold(
            appBar: AppBar(title: const Text('Flutter Demo')),
            body: const _Content()));
  }
}

Future<void> _showDialog(BuildContext context,
        {required int n, required int to}) =>
    showDialog<void>(
        context: context,
        barrierDismissible: false,
        builder: (dialogContext) => AlertDialog(
            title: Text('#$n', textAlign: TextAlign.center),
            content: _ModalContent(n: n, to: to)));

class _Content extends StatelessWidget {
  const _Content({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Center(
        child: ElevatedButton(
            onPressed: () async => await _showDialog(context, n: 1, to: 2),
            child: const Text('Please open two modals…')));
  }
}

final overriddenProvider = Provider.autoDispose((_) => true);
final signalProvider = StateProvider.autoDispose((_) => 0);

class _ModalContent extends HookConsumerWidget {
  const _ModalContent({Key? key, required this.n, required this.to})
      : super(key: key);

  final int n;
  final int to;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final state = useState(n.isOdd);
    ref.watch(signalProvider.state);

    return Column(
      mainAxisSize: MainAxisSize.min,
      children: [
        if (n < to)
          ElevatedButton(
              onPressed: () async {
                state.value = false;
                await _showDialog(context, n: n + 1, to: to);
                print('signals on #$n');
                ref.read(signalProvider.state).state++;
              },
              child: const Text('Tap to open more')),
        if (n == to)
          TextButton(
              onPressed: () => Navigator.pop(context),
              child: const Text('Tap to close me')),

        // Switch whether to wrap with ProviderScope or not by the state.
        if (state.value)
          _WatchContent(n: n, overrides: false)
        else
          ProviderScope(
              overrides: [overriddenProvider.overrideWithValue(false)],
              child: _WatchContent(n: n, overrides: true))
      ],
    );
  }
}

class _WatchContent extends HookConsumerWidget {
  const _WatchContent({required this.n, required this.overrides});

  final int n;
  final bool overrides;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    print('_WatchContent.build(#$n, overrides: $overrides)');
    ref.watch(overriddenProvider);
    return const SizedBox.shrink();
  }
}
```

```
======== Exception caught by widgets library =======================================================
The following _CastError was thrown building ProviderScope(dirty, state: ProviderScopeState#ba81a):
Null check operator used on a null value

The relevant error-causing widget was: 
  ProviderScope ProviderScope:file:///Users/tohru/Documents/src/projects/flutter/override_autodispose_provider/lib/main.dart:77:11
When the exception was thrown, this was the stack: 
#0      ProviderContainer.updateOverrides (package:riverpod/src/framework/container.dart:419:55)
#1      ProviderScopeState.build (package:flutter_riverpod/src/framework.dart:183:17)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4919:27)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4806:15)
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#6      StatefulElement.update (package:flutter/src/widgets/framework.dart:5009:5)
#7      Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#8      RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5825:32)
#9      MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6375:17)
#10     Element.updateChild (package:flutter/src/widgets/framework.dart:3530:15)
#11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4832:16)
#12     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4977:11)
#13     Element.rebuild (package:flutter/src/widgets/framework.dart:4529:5)
#14     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#15     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:891:21)
#16     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:370:5)
#17     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#18     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1083:9)
#19     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:997:5)
#23     _invoke (dart:ui/hooks.dart:151:10)
#24     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#25     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
====================================================================================================
```
**Expected behavior**

No exception happens.

**Comment by JimmyTai** [comment]
I met this problem too.

**Comment by rrousselGit** [comment]
A fix for this is planned.

**Comment by rrousselGit** [comment]
Thanks for your reproducible example. It has been massively helpful
