### ISSUE TITLE
Project doesn't compile if the type of certain providers is not explicitly specified 

### ISSUE THREAD

**Issue by UCetinkaya94** [rrousselGit/riverpod#1521]
**To Reproduce**
```dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

final progressProvider = Provider((ref) {
  return 0.5.clamp(0.0, 1.0);
});

void main() {
  runApp(
    const MaterialApp(
      home: Scaffold(),
    ),
  );
}
```
The type is inferred correctly as you can see here:

<img width="720" alt="Bildschirmfoto 2022-07-31 um 15 55 14" src="https://user-images.githubusercontent.com/67158575/182029709-29053e83-8777-4269-9ab7-f91171dda4f5.png">

There are no errors or warnings, but when you try to compile it fails with this message:

```
Unhandled exception:
Crash when compiling null,
at character offset null:
Null check operator used on a null value
#0      TypeInferrerImpl._inferInvocation (package:front_end/src/fasta/type_inference/type_inferrer.dart:2531:28)
#1      TypeInferrerImpl.inferInvocation (package:front_end/src/fasta/type_inference/type_inferrer.dart:2155:12)
#2      TypeInferrerImpl._inferInstanceMethodInvocation (package:front_end/src/fasta/type_inference/type_inferrer.dart:3295:40)
#3      TypeInferrerImpl.inferMethodInvocation (package:front_end/src/fasta/type_inference/type_inferrer.dart:3832:20)
#4      InferenceVisitor.visitMethodInvocation (package:front_end/src/fasta/kernel/inference_visitor.dart:2909:21)
#5      MethodInvocation.acceptInference (package:front_end/src/fasta/kernel/internal_ast.dart:4644:20)
#6      TypeInferrerImpl._inferExpression (package:front_end/src/fasta/type_inference/type_inferrer.dart:2030:27)
#7      TypeInferrerImpl.inferExpression (package:front_end/src/fasta/type_inference/type_inferrer.dart:2067:40)
#8      InferenceVisitor.visitReturnStatement (package:front_end/src/fasta/kernel/inference_visitor.dart:5947:61)
#9      ReturnStatement.accept (package:kernel/ast.dart:9864:43)
#10     TypeInferrerImpl.inferStatement (package:front_end/src/fasta/type_inference/type_inferrer.dart:4115:24)
#11     InferenceVisitor._visitStatements (package:front_end/src/fasta/kernel/inference_visitor.dart:542:20)
#12     InferenceVisitor.visitBlock (package:front_end/src/fasta/kernel/inference_visitor.dart:563:31)
#13     Block.accept (package:kernel/ast.dart:8885:43)
#14     TypeInferrerImpl.inferStatement (package:front_end/src/fasta/type_inference/type_inferrer.dart:4115:24)
#15     TypeInferrerImpl.inferLocalFunction (package:front_end/src/fasta/type_inference/type_inferrer.dart:2861:43)
#16     InferenceVisitor.visitFunctionNode (package:front_end/src/fasta/kernel/inference_visitor.dart:1380:21)
#17     InferenceVisitor.visitFunctionExpression (package:front_end/src/fasta/kernel/inference_visitor.dart:1411:9)
#18     FunctionExpression.accept1 (package:kernel/ast.dart:8283:9)
#19     TypeInferrerImpl._inferExpression (package:front_end/src/fasta/type_inference/type_inferrer.dart:2032:27)

#20     TypeInferrerImpl.inferExpression (package:front_end/src/fasta/type_inference/type_inferrer.dart:2067:40)
#21     TypeInferrerImpl._inferInvocation (package:front_end/src/fasta/type_inference/type_inferrer.dart:2428:46)
#22     TypeInferrerImpl.inferInvocation (package:front_end/src/fasta/type_inference/type_inferrer.dart:2155:12)
#23     InferenceVisitor.visitConstructorInvocation (package:front_end/src/fasta/kernel/inference_visitor.dart:700:49)
#24     ConstructorInvocation.accept1 (package:kernel/ast.dart:6383:9)
#25     TypeInferrerImpl._inferExpression (package:front_end/src/fasta/type_inference/type_inferrer.dart:2032:27)
#26     TypeInferrerImpl.inferExpression (package:front_end/src/fasta/type_inference/type_inferrer.dart:2067:40)
#27     _ImplicitFieldTypeRoot.computeType (package:front_end/src/fasta/kernel/implicit_field_type.dart:162:55)
#28     SourceFieldBuilder.inferType (package:front_end/src/fasta/source/source_field_builder.dart:456:47)
#29     SourceLoader.performTopLevelInference (package:front_end/src/fasta/source/source_loader.dart:2292:35)
#30     KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:531:14)
<asynchronous suspension>
#31     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#32     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:400:33)
<asynchronous suspension>
#33     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:68:50)
<asynchronous suspension>
#34     FrontendCompiler.compile (file:///opt/s/w/ir/x/w/sdk/pkg/frontend_server/lib/frontend_server.dart:562:11)
<asynchronous suspension>
#35     listenAndCompile.<anonymous closure> (file:///opt/s/w/ir/x/w/sdk/pkg/frontend_server/lib/frontend_server.dart:1199:11)
<asynchronous suspension>

#0      TypeInferrerImpl._inferInvocation (package:front_end/src/fasta/type_inference/type_inferrer.dart:2531:28)
#1      TypeInferrerImpl.inferInvocation (package:front_end/src/fasta/type_inference/type_inferrer.dart:2155:12)
#2      TypeInferrerImpl._inferInstanceMethodInvocation (package:front_end/src/fasta/type_inference/type_inferrer.dart:3295:40)
#3      TypeInferrerImpl.inferMethodInvocation (package:front_end/src/fasta/type_inference/type_inferrer.dart:3832:20)
#4      InferenceVisitor.visitMethodInvocation (package:front_end/src/fasta/kernel/inference_visitor.dart:2909:21)
#5      MethodInvocation.acceptInference (package:front_end/src/fasta/kernel/internal_ast.dart:4644:20)
#6      TypeInferrerImpl._inferExpression (package:front_end/src/fasta/type_inference/type_inferrer.dart:2030:27)
#7      TypeInferrerImpl.inferExpression (package:front_end/src/fasta/type_inference/type_inferrer.dart:2067:40)
#8      InferenceVisitor.visitReturnStatement (package:front_end/src/fasta/kernel/inference_visitor.dart:5947:61)
#9      ReturnStatement.accept (package:kernel/ast.dart:9864:43)
#10     TypeInferrerImpl.inferStatement (package:front_end/src/fasta/type_inference/type_inferrer.dart:4115:24)
#11     InferenceVisitor._visitStatements (package:front_end/src/fasta/kernel/inference_visitor.dart:542:20)
#12     InferenceVisitor.visitBlock (package:front_end/src/fasta/kernel/inference_visitor.dart:563:31)
#13     Block.accept (package:kernel/ast.dart:8885:43)
#14     TypeInferrerImpl.inferStatement (package:front_end/src/fasta/type_inference/type_inferrer.dart:4115:24)
#15     TypeInferrerImpl.inferLocalFunction (package:front_end/src/fasta/type_inference/type_inferrer.dart:2861:43)
#16     InferenceVisitor.visitFunctionNode (package:front_end/src/fasta/kernel/inference_visitor.dart:1380:21)
#17     InferenceVisitor.visitFunctionExpression (package:front_end/src/fasta/kernel/inference_visitor.dart:1411:9)
#18     FunctionExpression.accept1 (package:kernel/ast.dart:8283:9)
#19     TypeInferrerImpl._inferExpression (package:front_end/src/fasta/type_inference/type_inferrer.dart:2032:27)
#20     TypeInferrerImpl.inferExpression (package:front_end/src/fasta/type_inference/type_inferrer.dart:2067:40)
#21     TypeInferrerImpl._inferInvocation (package:front_end/src/fasta/type_inference/type_inferrer.dart:2428:46)
#22     TypeInferrerImpl.inferInvocation (package:front_end/src/fasta/type_inference/type_inferrer.dart:2155:12)
#23     InferenceVisitor.visitConstructorInvocation (package:front_end/src/fasta/kernel/inference_visitor.dart:700:49)
#24     ConstructorInvocation.accept1 (package:kernel/ast.dart:6383:9)
#25     TypeInferrerImpl._inferExpression (package:front_end/src/fasta/type_inference/type_inferrer.dart:2032:27)
#26     TypeInferrerImpl.inferExpression (package:front_end/src/fasta/type_inference/type_inferrer.dart:2067:40)
#27     _ImplicitFieldTypeRoot.computeType (package:front_end/src/fasta/kernel/implicit_field_type.dart:162:55)

#28     SourceFieldBuilder.inferType (package:front_end/src/fasta/source/source_field_builder.dart:456:47)
#29     SourceLoader.performTopLevelInference (package:front_end/src/fasta/source/source_loader.dart:2292:35)
#30     KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:531:14)
<asynchronous suspension>
#31     withCrashReporting (package:front_end/src/fasta/crash.dart:122:12)
<asynchronous suspension>
#32     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:400:33)
<asynchronous suspension>
#33     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:68:50)
<asynchronous suspension>
#34     FrontendCompiler.compile (file:///opt/s/w/ir/x/w/sdk/pkg/frontend_server/lib/frontend_server.dart:562:11)
<asynchronous suspension>
#35     listenAndCompile.<anonymous closure> (file:///opt/s/w/ir/x/w/sdk/pkg/frontend_server/lib/frontend_server.dart:1199:11)
<asynchronous suspension>

the Dart compiler exited unexpectedly.
the Dart compiler exited unexpectedly.
Exited (1)
```

Specifying the type solves the problem:

```dart
final progressProvider = Provider<double>((ref) {
  return 0.5.clamp(0.0, 1.0);
});
```

In this case it has to do with `clamp` but I don't know why exactly.

**Comment by rrousselGit** [comment]
That's a Dart bug. Nothing I can't do
Try raising an issue on the Dart SDK instead
