### ISSUE TITLE
Cannot get renderObject of inactive element.

### ISSUE THREAD

**Issue by imcouri** [rrousselGit/riverpod#1526]
**Describe the bug**
Whenever I click a input field inside a consumer widget(both stateful and stateless) the error `Cannot get renderObject of inactive element.` is thrown

```
======== Exception caught by animation library =====================================================
The following assertion was thrown while notifying listeners for AnimationController:
Cannot get renderObject of inactive element.

In order for an element to have a valid renderObject, it must be active, which means it is part of the tree.
Instead, this element is in the _ElementLifecycle.inactive state.
If you called this method from a State object, consider guarding it with State.mounted.
The findRenderObject() method was called for the following element: _Editable-[GlobalKey#ca8cb]
  dependencies: [_LocalizationsScope-[GlobalKey#2471d]]
  renderObject: RenderEditable#49d80 relayoutBoundary=up19 NEEDS-LAYOUT DETACHED
When the exception was thrown, this was the stack: 
#0      Element.findRenderObject.<anonymous closure> (package:flutter/src/widgets/framework.dart:4039:9)
#1      Element.findRenderObject (package:flutter/src/widgets/framework.dart:4052:6)
#2      EditableTextState.renderEditable (package:flutter/src/widgets/editable_text.dart:2902:69)
#3      EditableTextState._onCursorColorTick (package:flutter/src/widgets/editable_text.dart:2645:5)
#4      AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:155:19)
#5      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:830:5)
#6      Ticker._tick (package:flutter/src/scheduler/ticker.dart:238:12)
#7      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1146:15)
#8      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1059:11)
#9      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:614:13)
#10     SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1057:17)
#11     SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:976:5)
#15     _invoke1 (dart:ui/hooks.dart:170:10)
#16     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:286:5)
#17     _beginFrame (dart:ui/hooks.dart:104:31)
(elided 3 frames from dart:async)
The AnimationController notifying listeners was: AnimationController#57835(▶ 0.891)
====================================================================================================
```

**To Reproduce**
```
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

class SignUpPage extends ConsumerWidget {
  const SignUpPage({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context,WidgetRef ref) {
    return Scaffold(
      resizeToAvoidBottomInset: true,
      backgroundColor: Colors.white,
      appBar: AppBar(
        elevation: 0,
        backgroundColor: Colors.white,
        leading: IconButton(
          onPressed: () {
            Navigator.pop(context);
          },
          icon: const Icon(Icons.arrow_back_ios, size: 20, color: Colors.black,),
        ),
      ),
      body: SingleChildScrollView(
        child: Container(
          padding: const EdgeInsets.symmetric(horizontal: 40),
          height: MediaQuery.of(context).size.height - 50,
          width: double.infinity,
          child: Column(
            mainAxisAlignment: MainAxisAlignment.spaceEvenly,
            children: <Widget>[
              Column(
                children: <Widget>[
                  const Text("Sign up", style: TextStyle(
                      fontSize: 30,
                      fontWeight: FontWeight.bold
                  ),),
                  const SizedBox(height: 20,),
                  Text("Create your account", style: TextStyle(
                      fontSize: 15,
                      color: Colors.grey[700]
                  ),),
                ],
              ),
              Column(
                children: <Widget>[
                  makeInput(label: "Email"),
                  makeInput(label: "Password", obscureText: true),
                  makeInput(label: "Confirm Password", obscureText: true)
                ],
              ),
              Container(
                padding: const EdgeInsets.only(top: 3, left: 3),
                decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(50),
                    border: const Border(
                      bottom: BorderSide(color: Colors.black),
                      top: BorderSide(color: Colors.black),
                      left: BorderSide(color: Colors.black),
                      right: BorderSide(color: Colors.black),
                    )
                ),
                child: MaterialButton(
                  minWidth: double.infinity,
                  height: 60,
                  onPressed: () async{
                  },
                  color: Theme.of(context).primaryColor,
                  elevation: 0,
                  shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(50)
                  ),
                  child: const Text("Sign up", style: const TextStyle(
                      fontWeight: FontWeight.w600,
                      fontSize: 18
                  ),),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget makeInput({label, obscureText = false}) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        Text(label, style: const TextStyle(
            fontSize: 15,
            fontWeight: FontWeight.w400,
            color: Colors.black87
        ),),
        const SizedBox(height: 5,),
        TextField(
          obscureText: obscureText,
          decoration: const InputDecoration(
            contentPadding: EdgeInsets.symmetric(vertical: 0, horizontal: 10),
            enabledBorder: OutlineInputBorder(
                borderSide: BorderSide(color: Colors.grey)
            ),
            border: OutlineInputBorder(
                borderSide: BorderSide(color: Colors.grey)
            ),
          ),
        ),
        const SizedBox(height: 30,),
      ],
    );
  }
}
```

For example, this page throws this error when a text input is clicked, and the keyboard gets opened. 
I've tried it on both IOS simulator and a real iPhone and it happens on both of them.

**Comment by rrousselGit** [comment]
Hello!

What does this have to do with Riverpod?
Riverpod isn't reading renderobjects.

**Comment by rrousselGit** [comment]
I'll close this as, like you can see from the stackTrace, this is unrelated to Riverpod.

Your problem most likely would happen without Riverpod
