### ISSUE TITLE
[Possible bug] AsyncNotifier leaves a Timer open when testing

### ISSUE THREAD

**Issue by lucavenir** [rrousselGit/riverpod#1732]
**Describe the bug**
`AsyncNotifier` works fine, but as I try to test it, it leaves a pending `Timer` after the widget tree is disposed. This makes my tests fail. Note how the application works fine, but the test don't. I'll paste the error below

**To Reproduce**
Here's a full reproducible example: [link](https://github.com/lucavenir/riverpod2_possible_bug_repro).
To reproduce, run all the tests in there

**Expected behavior**
Those tests should either pass or fail, but I wouldn't expect that error.

**Further note**
I was trying to reproduce [this GoRouter bug](https://github.com/flutter/flutter/issues/112798) in relation with Riverpod 2.0 (I'm trying to add another GoRouter + Riverpod 2 example).

I'm writing this as it might be related (I'm not sure): I have the same issue mentioned [there](https://github.com/flutter/flutter/issues/112798#issue-1394670449), but only when testing my application; when running it, everything's fine.

**Stacktrace**
<details>
<summary>Console errors</summary>

```
Pending timers:
Timer (duration: 0:00:01.000000, periodic: false), created:
#0      new FakeTimer._ (package:fake_async/fake_async.dart:308:62)
#1      FakeAsync._createTimer (package:fake_async/fake_async.dart:252:27)
#2      FakeAsync.run.<anonymous closure> (package:fake_async/fake_async.dart:185:19)
#6      AuthNotifier.build (package:go_router_range_error/state/auth_state.dart:15:45)
#7      AsyncNotifierProviderImpl.runNotifierBuild (package:riverpod/src/async_notifier/base.dart:100:43)
#8      AsyncNotifierProviderElement.create.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:332:24)
#9      Result.guard (package:riverpod/src/result.dart:18:28)
#10     FutureHandlerProviderElementMixin.handleFuture (package:riverpod/src/async_notifier/base.dart:212:35)
#11     AsyncNotifierProviderElement.create.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:331:27)
#12     ResultData.when (package:riverpod/src/result.dart:68:16)
#13     AsyncNotifierProviderElement.create (package:riverpod/src/async_notifier/base.dart:326:20)
#14     ProviderElementBase.buildState (package:riverpod/src/framework/element.dart:414:7)
#15     ProviderElementBase.mount (package:riverpod/src/framework/element.dart:236:5)
#16     _StateReader._create (package:riverpod/src/framework/container.dart:53:11)
#17     _StateReader.getElement (package:riverpod/src/framework/container.dart:41:52)
#18     ProviderContainer.readProviderElement (package:riverpod/src/framework/container.dart:494:19)
#19     ProviderElementBase.readProviderElement (package:riverpod/src/framework/element.dart:701:23)
#20     ProviderBase.addListener (package:riverpod/src/framework/provider_base.dart:75:26)
#21     ProviderElementBase.listen (package:riverpod/src/framework/element.dart:736:23)
#22     new _RouterNotifier (package:go_router_range_error/router.dart:26:23)
#23     routerProvider.<anonymous closure> (package:go_router_range_error/router.dart:13:18)
#24     Provider._create (package:riverpod/src/provider/base.dart:40:57)
#25     ProviderElement.create (package:riverpod/src/provider/base.dart:271:23)
#26     ProviderElementBase.buildState (package:riverpod/src/framework/element.dart:414:7)
#27     ProviderElementBase.mount (package:riverpod/src/framework/element.dart:236:5)
#28     _StateReader._create (package:riverpod/src/framework/container.dart:53:11)
#29     _StateReader.getElement (package:riverpod/src/framework/container.dart:41:52)
#30     ProviderContainer.readProviderElement.<anonymous closure> (package:riverpod/src/framework/container.dart:455:40)
#31     ProviderContainer.readProviderElement (package:riverpod/src/framework/container.dart:490:8)
#32     ProviderBase.addListener (package:riverpod/src/framework/provider_base.dart:75:26)
#33     ProviderContainer.listen (package:riverpod/src/framework/container.dart:298:21)
#34     ConsumerStatefulElement.watch.<anonymous closure> (package:flutter_riverpod/src/consumer.dart:506:25)
#35     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:527:23)
#36     ConsumerStatefulElement.watch (package:flutter_riverpod/src/consumer.dart:499:26)
#37     App.build (package:go_router_range_error/app.dart:13:24)
#38     _ConsumerState.build (package:flutter_riverpod/src/consumer.dart:427:19)
#39     StatefulElement.build (package:flutter/src/widgets/framework.dart:4992:27)
#40     ConsumerStatefulElement.build (package:flutter_riverpod/src/consumer.dart:488:20)
#41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4878:15)
#42     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#43     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#44     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4859:5)
#45     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5041:11)
#46     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4853:5)
...     Normal element mounting (7 frames)
#53     _UncontrolledProviderScopeElement.mount (package:flutter_riverpod/src/framework.dart:310:11)
...     Normal element mounting (9 frames)
#62     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
#63     Element.updateChild (package:flutter/src/widgets/framework.dart:3586:20)
#64     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1195:16)
#65     RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:1172:5)
#66     RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:1186:7)
#67     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#68     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:19)
#69     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1191:19)
#70     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#71     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#72     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#73     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:1057:9)
#76     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#77     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:1043:27)
#78     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:554:22)
#81     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#82     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:551:27)
#83     main.<anonymous closure>.<anonymous closure> (file:///home/venir/Documents/Flutter/go_router_range_error/test/widget_test.dart:8:20)
#84     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:171:29)
<asynchronous suspension>
<asynchronous suspension>
(elided 8 frames from dart:async and package:stack_trace)

══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
A Timer is still pending even after the widget tree was disposed.
'package:flutter_test/src/binding.dart':
Failed assertion: line 1299 pos 12: '!timersPending'

When the exception was thrown, this was the stack:
#2      AutomatedTestWidgetsFlutterBinding._verifyInvariants (package:flutter_test/src/binding.dart:1299:12)
#3      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:857:7)
<asynchronous suspension>
(elided 2 frames from class _AssertionError)

The test description was:
  startup with a loading screen
════════════════════════════════════════════════════════════════════════════════════════════════════
Test failed. See exception logs above.
```

</details>

**Comment by rrousselGit** [comment]
The stackTrace seems to indicate that the issue is your `Future.delayed`

**Comment by rrousselGit** [comment]
For info, Future.delayed internally creates a timer. So it it's still pending, that could be the issue

**Comment by lucavenir** [comment]
Hi @rrousselGit thank you for the quick response.

I tried to call some real public API instead, and error persists. The repo is now updated. Internally I use `Dio`, which itself uses a timer, too (apparently), but I can't wrap my around this error.

Am I missing some testing practices?

**Comment by rrousselGit** [comment]
The error clearly blames Dio.
It's testWidgets making your life difficult, because it mocks async/awaits stuff doing Zone hacks. If you used a plain `test` it'd work

I'm not sure how `testWidgets` deals with Dio. But to begin with, I believe Flutter tries to disable the network during widget tests.

 
Anyway changing `pump` to `pumpAndSettle` seems to remove the issue.

**Comment by lucavenir** [comment]
Ok, so it just was a coincidence.

Thanks, sorry if I blamed Riverpod but I actually didn't know where to look!
