### ISSUE TITLE
Iterating a List on ref.onDispose and build will throw error

### ISSUE THREAD

**Issue by SuperPenguin** [rrousselGit/riverpod#1881]
**Describe the bug**
Iterating a List state on Notifier will throw Concurrent modification during iteration error when done in both ref.onDispose and build body

**To Reproduce**

Code
```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

part 'main.g.dart';

Future<void> main() async {
  runApp(
    const ProviderScope(
      child: App(),
    ),
  );
}

class App extends StatelessWidget {
  const App({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      routes: {
        '/': (context) => const HomeScreen(),
      },
    );
  }
}

@Riverpod(keepAlive: true)
class MyController extends _$MyController {
  MyController();

  @override
  List<int> build() {
    ref.onDispose(() {
      removeListener();
    });

    state = [1, 2, 3];

    addListener();

    return state;
  }

  void addListener() {
    for (final i in state) {
      if (kDebugMode) {
        print('Add $i');
      }
    }
  }

  void removeListener() {
    for (final i in state) {
      if (kDebugMode) {
        print('Remove $i');
      }
    }
  }
}

class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Consumer(
          builder: (context, ref, child) {
            final state = ref.watch(myControllerProvider);

            return Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                for (final i in state) Text(i.toString()),
                ElevatedButton(
                  onPressed: () {
                    if (kDebugMode) {
                      print('Invalidate');
                    }
                    ref.invalidate(myControllerProvider);
                  },
                  child: const Text('Invalidate'),
                ),
              ],
            );
          },
        ),
      ),
    );
  }
}
```

Debug console output
```
flutter: Add 1
flutter: Add 2
flutter: Add 3
flutter: Invalidate
flutter: Add 1
flutter: Add 2
flutter: Add 3
flutter: Remove 1
flutter: Remove 2
flutter: Remove 3
```

Stack trace
```
════════ Exception caught by gesture ═══════════════════════════════════════════
The following ConcurrentModificationError was thrown while handling a gesture:
Concurrent modification during iteration: Instance(length:2) of '_GrowableList'.

When the exception was thrown, this was the stack
#0      List.forEach (dart:core-patch/growable_array.dart:417:36)
#1      ProviderElementBase.runOnDispose
package:riverpod/…/framework/element.dart:895
#2      ProviderElementBase.invalidateSelf
package:riverpod/…/framework/element.dart:289
#3      ProviderContainer.invalidate
package:riverpod/…/framework/container.dart:312
#4      ConsumerStatefulElement.invalidate
package:flutter_riverpod/src/consumer.dart:562
#5      HomeScreen.build.<anonymous closure>.<anonymous closure>
package:riverpodtest/main.dart:83
#6      _InkResponseState.handleTap
package:flutter/…/material/ink_well.dart:1072
#7      GestureRecognizer.invokeCallback
package:flutter/…/gestures/recognizer.dart:253
#8      TapGestureRecognizer.handleTapUp
package:flutter/…/gestures/tap.dart:627
#9      BaseTapGestureRecognizer._checkUp
package:flutter/…/gestures/tap.dart:306
#10     BaseTapGestureRecognizer.handlePrimaryPointer
package:flutter/…/gestures/tap.dart:239
#11     PrimaryPointerGestureRecognizer.handleEvent
package:flutter/…/gestures/recognizer.dart:615
#12     PointerRouter._dispatch
package:flutter/…/gestures/pointer_router.dart:98
#13     PointerRouter._dispatchEventToRoutes.<anonymous closure>
package:flutter/…/gestures/pointer_router.dart:143
#14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:617:13)
```

**Expected behavior**
This should not throw

**Comment by rrousselGit** [comment]
The list seems unrelated.

It appears to be caused by reading `state` in `onDispose`. Likely because reading `state` forces the provider to recompute. Which ends-up calling `ref.onDispose` again to register the new listener.

**Comment by sososdk** [comment]
Has any updates?

**Comment by sososdk** [comment]
Hi @rrousselGit thank you so much for such a great library. Do you have any plans to fix this issue? Or there could be a better way to avoid this issue.

**Comment by rrousselGit** [comment]
You're not supposed to read the state inside onDispose.

Whatever needs disposing should not be inside obtained through ref.state, but through a local variable created previously.

I'm not quite sure what I'll do with this error yet.
