### ISSUE TITLE
Cannot modify unmodifiable map Exception in debug mode

### ISSUE THREAD

**Issue by sma** [rrousselGit/riverpod#2003]
I get an `Unsupported operation: Cannot modify unmodifiable map` exception when running the app in debug mode.

I'm using `flutter_riverpod` 2.1.1 with the latest Flutter version:

```
[✓] Flutter (Channel master, 3.7.0-8.0.pre.6, on macOS 13.1 22C65 darwin-arm64, locale de-DE)
    • Flutter version 3.7.0-8.0.pre.6 on channel master at /Users/sma/Work/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 028c6e29e0 (6 hours ago), 2022-12-13 21:18:21 -0800
    • Engine revision 14194c40ec
    • Dart version 3.0.0 (build 3.0.0-19.0.dev)
    • DevTools version 2.20.0
```

on macOS 13.2 and Xcode 14.1 (not yet 14.2).

**To Reproduce**

```
void main() async {
  runApp(ProviderScope(child: Container()));
}
```

Here's the exception:

```
flutter: The following UnsupportedError was thrown attaching to the render tree:
flutter: Unsupported operation: Cannot modify unmodifiable map
flutter: 
flutter: When the exception was thrown, this was the stack:
flutter: #0      _UnmodifiableMapMixin.[]= (dart:collection/maps.dart:269:5)
flutter: #1      postEvent (dart:developer/extension.dart:183:12)
flutter: #2      debugPostEvent (package:riverpod/src/devtool.dart:22:15)
flutter: #3      RiverpodBinding.containers= (package:riverpod/src/devtool.dart:84:5)
flutter: #4      new ProviderContainer.<anonymous closure> (package:riverpod/src/framework/container.dart:124:39)
flutter: #5      new ProviderContainer (package:riverpod/src/framework/container.dart:129:8)
flutter: #6      ProviderScopeState.initState (package:flutter_riverpod/src/framework.dart:179:17)
flutter: #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5125:55)
flutter: #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4968:5)
flutter: #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3977:16)
flutter: #10     Element.updateChild (package:flutter/src/widgets/framework.dart:3706:18)
flutter: #11     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1176:16)
flutter: #12     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1145:5)
flutter: #13     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1092:18)
flutter: #14     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2706:19)
flutter: #15     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1091:13)
flutter: #16     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:926:7)
flutter: #17     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:906:7)
flutter: #21     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:26)
flutter: (elided 3 frames from class _Timer and dart:async-patch)
```

**Expected behavior**

No exception. Note: The above exception only occurs in debug mode.

**Comment by sma** [comment]
It looks like [postEvent](https://api.flutter.dev/flutter/dart-developer/postEvent.html) whats to modify its second argument which is a `const` in this case. So perhaps this is a bug in Flutter?  In the `developer` package, [it does modify](https://github.com/dart-lang/sdk/blob/main/sdk/lib/developer/extension.dart#L183)  its second argument. 

This change was introduced yesterday!

**Comment by sma** [comment]
Therefore, I filed https://github.com/dart-lang/sdk/issues/50713 now.

**Comment by justinmc** [comment]
I see the same thing on Linux.  I think riverpod won't work at all on Flutter's master channel right now.
