### ISSUE TITLE
Cast error when stubbing a generated provider family

### ISSUE THREAD

**Issue by remonh87** [rrousselGit/riverpod#2047]
**Describe the bug**
When running the reproduction test I receive a cast error.  It can be that I misunderstood the usage of the generated provider but couldn't get it out of the docs. Let me know and I can help improve the docs.

<details><summary>Tap to expand stacktrace</summary>
<code>
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following _CastError was thrown building SimpleWidget(dirty, dependencies:
[UncontrolledProviderScope], state: _ConsumerState#f3702):
type '_ProductNotifierStub' is not a subtype of type 'AutoDisposeNotifier<int>' in type cast

The relevant error-causing widget was:
  SimpleWidget
When the exception was thrown, this was the stack:
#1      _ExternalProviderSubscription.read (package:riverpod/src/framework/provider_base.dart:179:29)
#2      ConsumerStatefulElement.watch (package:flutter_riverpod/src/consumer.dart:560:8)
#3      SimpleWidget.build (package:recipe_configuration_ui_v2/src/repo.dart:16:23)
#4      _ConsumerState.build (package:flutter_riverpod/src/consumer.dart:477:19)
#5      StatefulElement.build (package:flutter/src/widgets/framework.dart:4992:27)
#6      ConsumerStatefulElement.build (package:flutter_riverpod/src/consumer.dart:538:20)
#7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4878:15)
#8      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#9      Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#10     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4859:5)
#11     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5041:11)
#12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4853:5)
...     Normal element mounting (25 frames)
#37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
#38     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6435:36)
#39     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6447:32)
...     Normal element mounting (379 frames)
#418    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
#419    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6435:36)
#420    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6447:32)
...     Normal element mounting (422 frames)
#842    _UncontrolledProviderScopeElement.mount (package:flutter_riverpod/src/framework.dart:309:11)
...     Normal element mounting (9 frames)
#851    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
#852    Element.updateChild (package:flutter/src/widgets/framework.dart:3586:20)
#853    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1195:16)
#854    RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:1172:5)
#855    RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:1186:7)
#856    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#857    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:19)
#858    AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1191:19)
#859    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#860    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#861    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#862    AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:1057:9)
#865    TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#866    AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:1043:27)
#867    WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:554:22)
#870    TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#871    WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:551:27)
#872    main.<anonymous closure> (repo_test.dart:8:18)
#873    testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:171:29)
#875    ProviderContainer.listen (package:riverpod/src/framework/container.dart:273:21)
#876    ConsumerStatefulElement.watch.<anonymous closure> (package:flutter_riverpod/src/consumer.dart:556:25)
#877    _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:527:23)
#878    ConsumerStatefulElement.watch (package:flutter_riverpod/src/consumer.dart:549:26)
#879    SimpleWidget.build (package:recipe_configuration_ui_v2/src/repo.dart:16:23)
#880    _ConsumerState.build (package:flutter_riverpod/src/consumer.dart:477:19)
#881    StatefulElement.build (package:flutter/src/widgets/framework.dart:4992:27)
#882    ConsumerStatefulElement.build (package:flutter_riverpod/src/consumer.dart:538:20)
#883    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4878:15)
#884    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#885    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#886    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4859:5)
#887    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5041:11)
#888    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4853:5)
...     Normal element mounting (25 frames)
#913    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
#914    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6435:36)
#915    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6447:32)
...     Normal element mounting (379 frames)
#1294   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
#1295   MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6435:36)
#1296   MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6447:32)
...     Normal element mounting (422 frames)
#1718   _UncontrolledProviderScopeElement.mount (package:flutter_riverpod/src/framework.dart:309:11)
...     Normal element mounting (9 frames)
#1727   Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
#1728   Element.updateChild (package:flutter/src/widgets/framework.dart:3586:20)
#1729   RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1195:16)
#1730   RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:1172:5)
#1731   RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:1186:7)
#1732   Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#1733   BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:19)
#1734   AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1191:19)
#1735   RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#1736   SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#1737   SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#1738   AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:1057:9)
#1741   TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#1742   AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:1043:27)
#1743   WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:554:22)
#1746   TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:71:41)
#1747   WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:551:27)
#1748   main.<anonymous closure> (repo_test.dart:8:18)
#1749   testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:171:29)
#1751   testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:170:25)
#1752   TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:841:19)
#1754   TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:831:5)
#1757   TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:820:14)
#1758   AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1247:24)
#1759   FakeAsync.run.<anonymous closure>.<anonymous closure> (package:fake_async/fake_async.dart:182:54)
#1764   withClock (package:clock/src/default.dart:52:10)
#1765   FakeAsync.run.<anonymous closure> (package:fake_async/fake_async.dart:182:22)
#1770   FakeAsync.run (package:fake_async/fake_async.dart:182:7)
#1771   AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1244:15)
#1772   testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:164:24)
#1773   Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:215:19)
#1775   Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:214:9)
#1780   Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:213:13)
#1781   Invoker._waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:257:15)
#1786   Invoker._waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:254:5)
#1787   Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:391:17)
#1789   Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:389:11)
#1794   Invoker._onRun.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:380:9)
#1795   Invoker._guardIfGuarded (package:test_api/src/backend/invoker.dart:423:15)
#1796   Invoker._onRun.<anonymous closure> (package:test_api/src/backend/invoker.dart:379:7)
#1803   Invoker._onRun (package:test_api/src/backend/invoker.dart:378:11)
#1804   LiveTestController.run (package:test_api/src/backend/live_test_controller.dart:153:11)
#1805   RemoteListener._runLiveTest.<anonymous closure> (package:test_api/src/backend/remote_listener.dart:273:16)
#1810   RemoteListener._runLiveTest (package:test_api/src/backend/remote_listener.dart:272:5)
#1811   RemoteListener._serializeTest.<anonymous closure> (package:test_api/src/backend/remote_listener.dart:220:7)
#1829   _GuaranteeSink.add (package:stream_channel/src/guarantee_channel.dart:125:12)
#1830   new _MultiChannel.<anonymous closure> (package:stream_channel/src/multi_channel.dart:159:31)
#1832   CastStreamSubscription._onData (dart:_internal/async_cast.dart:85:11)
#1858   new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1144:21)
#1864   _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:332:23)
#1865   _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:226:46)
#1873   _Socket._onData (dart:io-patch/socket_patch.dart:2324:41)
#1880   new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1849:33)
#1881   _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1322:14)
(elided 108 frames from dart:async and package:stack_trace)

Exited (1)
</code></details>

**To Reproduce**
Widget

```dart
class SimpleWidget extends ConsumerWidget {
  const SimpleWidget({
    required this.product,
    super.key,
  });

  final Product product;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final value = ref.watch(productNotifierProvider(Product.coffee));
    return Scaffold(
      body: Text('value: $value'),
    );
  }
}

@riverpod
class ProductNotifier extends _$ProductNotifier {
  @override
  int build(Product product) {
    switch (product) {
      case Product.iceCream:
        return 0;
      case Product.coffee:
        return 1;
    }
  }
}

enum Product { iceCream, coffee }
```
Test
```dart
void main() {
  testWidgets('Example test', (tester) async {
    await tester.pumpWidget(
      ProviderScope(
        overrides: [
          productNotifierProvider(Product.coffee)
              .overrideWith(_ProductNotifierStub.new)
        ],
        child: const MaterialApp(
          home: Scaffold(
            body: SimpleWidget(
              product: Product.coffee,
            ),
          ),
        ),
      ),
    );

    await tester.pumpAndSettle();

    expect(find.text('value: 1'), findsOneWidget);
  });
}

class _ProductNotifierStub extends ProductNotifier {
  @override
  int build(Product product) {
    return 1;
  }
}
```

**Expected behavior**
Since dart analyzer sees no issues I would expect the test to pass.

**Comment by pawlowskim** [comment]
@remonh87 Did you found any workaround?

**Comment by tomadimitrie** [comment]
@remonh87 @pawlowskim

Found a workaround, will mention this in the original issue as well.

```dart
class MockUserItemModel extends UserItemModel
    implements AutoDisposeAsyncNotifier<UserRowState> {  
  @override
  Future<UserRowState> build([String? id]) async {
    return UserRowStateNone();
  }
}
```

I ended up implementing the interface manually, and making the build argument optional to satisfy both `UserItemModel#build` and `AutoDisposeAsyncNotifier#build`. Not a very convenient solution... but it works

**Comment by rrousselGit** [comment]
This should be fixed now.
