### ISSUE TITLE
overriding an autodispose provider with a non-disposable one causes exception

### ISSUE THREAD

**Issue by raminsafaei** [rrousselGit/riverpod#2149]
**Describe the bug**
I use providerscope quite extensively and had multiple abstractions on statenotifier and used it in different parts of the app, some places as autodispose and some other parts as a long-lived provider. I believe in previous versions of provider(before adding overrideWith) it wasnt possible to override an autodispose provider with one that wasnt autodispose. in recent versions and with overrideWith however its possible and I did that, turns out disposition of autodispose provider(thats being overriden) causes the main provider to get disposed as well(without notifing onDispose callback or logging in providerobserver!)

**To Reproduce**
sorry code is a bit verbose and long
<details>
<summary>code</summary>

```dart
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';

void main() {
  final container = ProviderContainer();
  runApp(
    ProviderScope(parent: container, child: const MyApp()),
  );
}

abstract class BaseNotif extends StateNotifier<int> {
  BaseNotif(super.state);

  void increment() {
    state = ++state;
  }

  @override
  void dispose() {
    print('disposing $runtimeType');
    super.dispose();
  }
}

final disposableBaseNotifProvider =
    StateNotifierProvider.autoDispose<BaseNotif, int>((ref) {
  throw UnimplementedError('');
});

class FirstImplNotifier extends BaseNotif {
  FirstImplNotifier(super.state);

  static final provider = StateNotifierProvider<FirstImplNotifier, int>((ref) {
    ref.onCancel(() {
      print('onCancel first');
    });
    ref.onDispose(() {
      print('onDispose first');
    });
    return FirstImplNotifier(0);
  });
}

class SecondImplNotifier extends BaseNotif {
  SecondImplNotifier(super.state);

  static final provider = StateNotifierProvider<SecondImplNotifier, int>((ref) {
    ref.onCancel(() {
      print('onCancel second');
    });
    ref.onDispose(() {
      print('onDispose second');
    });
    return SecondImplNotifier(0);
  });
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      routerConfig: router,
    );
  }
}

class WrapperPage extends HookConsumerWidget {
  const WrapperPage(this.child, {super.key});
  final Widget child;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final selected = GoRouter.of(context).location.contains('first') ? 0 : 1;
    return Scaffold(
      body: child,
      bottomNavigationBar: NavigationBar(
        destinations: const [
          NavigationDestination(
            label: 'first',
            icon: Icon(Icons.abc_outlined),
          ),
          NavigationDestination(
            label: 'second',
            icon: Icon(Icons.security),
          ),
        ],
        onDestinationSelected: (value) {
          if (value == 0) {
            context.go('/first');
          } else {
            context.go('/second');
          }
        },
        selectedIndex: selected,
      ),
    );
  }
}

class FirstImplPage extends HookConsumerWidget {
  const FirstImplPage({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final state = ref.watch(FirstImplNotifier.provider);
    return ProviderScope(
      overrides: [
        disposableBaseNotifProvider.overrideWith(
          (ref) => ref.watch(FirstImplNotifier.provider.notifier),
        )
      ],
      child: Column(
        children: [
          Text('first'),
          InnerWidgetUsingDisposable(),
        ],
      ),
    );
  }
}

class SecondImplPage extends HookConsumerWidget {
  const SecondImplPage({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final state = ref.watch(SecondImplNotifier.provider);
    return ProviderScope(
      overrides: [
        disposableBaseNotifProvider.overrideWith(
          (ref) => ref.watch(SecondImplNotifier.provider.notifier),
        )
      ],
      child: Column(
        children: [
          Text('second'),
          InnerWidgetUsingDisposable(),
        ],
      ),
    );
  }
}

class InnerWidgetUsingDisposable extends HookConsumerWidget {
  const InnerWidgetUsingDisposable({super.key});
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final count = ref.watch(disposableBaseNotifProvider);
    return Column(
      children: [
        Text('count: $count'),
        TextButton(
          child: Text('increment'),
          onPressed: ref.read(disposableBaseNotifProvider.notifier).increment,
        )
      ],
    );
  }
}

final router = GoRouter(
  initialLocation: '/first',
  routes: [
    ShellRoute(
      builder: (context, state, child) {
        return WrapperPage(child);
      },
      routes: [
        GoRoute(
          path: '/first',
          pageBuilder: (context, state) {
            return const NoTransitionPage(
              child: FirstImplPage(),
            );
          },
        ),
        GoRoute(
          path: '/second',
          pageBuilder: (context, state) {
            return const NoTransitionPage(
              child: SecondImplPage(),
            );
          },
        ),
      ],
    ),
  ],
);
```

</details>

<details>
<summary>flutter doctor</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.1, on Microsoft Windows [Version 10.0.22000.1516], locale en-US)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Build Tools 2022 17.4.4)
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.75.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

</details>

using hooks_riverpod: ^2.1.3

**Expected behavior**
I think we should get a warning when trying to override an autodisposable provider with an alwaysalive one or it shouldnt call dispose function of main provider

**Comment by raminsafaei** [comment]
I was initially trying to replicate the same setup I have in my app here and didn't actually test different parts in this simple code. but I've noticed that it actually doesn't have anything to do with provider being autoDispose, it just disposes provider onCancel. so in the above code if you remove autoDispose from disposableBaseNotifProvider it still gets disposed (when removed from widget tree)
<details>
<summary>debug console log</summary>


```
Restarted application in 542ms.
flutter: disposing FirstImplNotifier
flutter: onCancel first

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building UncontrolledProviderScope:
Got a stack frame from package:stack_trace, where a vm or web frame was expected. This can happen if FlutterError.demangleStackTrace was not set in an environment that propagates non-standard stack traces to the framework, such as during tests.
'package:flutter/src/foundation/stack_frame.dart':
Failed assertion: line 192 pos 7: 'line != '===== asynchronous gap ===========================''


The relevant error-causing widget was
ProviderScope
When the exception was thrown, this was the stack
#2      StackFrame.fromStackTraceLine
#3      MappedIterator.moveNext (dart:_internal/iterable.dart:393:20)
#4      WhereTypeIterator.moveNext (dart:_internal/iterable.dart:871:20)
#5      new _GrowableList._ofOther (dart:core-patch/growable_array.dart:202:26)
#6      new _GrowableList.of (dart:core-patch/growable_array.dart:152:26)
#7      new List.of (dart:core-patch/array_patch.dart:52:28)
#8      Iterable.toList (dart:core/iterable.dart:470:12)
#9      StackFrame.fromStackString
#10     FlutterError.defaultStackFilter
#11     DiagnosticsStackTrace._applyStackFilter
#12     new DiagnosticsStackTrace
#13     FlutterErrorDetails.debugFillProperties
#14     DiagnosticableNode.builder.<anonymous closure>
#15     DiagnosticableNode.builder
#16     _FlutterErrorDetailsNode.builder
#17     DiagnosticableNode.emptyBodyDescription
#18     DiagnosticsNode.toJsonMap.<anonymous closure>
#19     DiagnosticsNode.toJsonMap
#20     WidgetInspectorService._nodeToJson
#21     WidgetInspectorService._reportStructuredError
#22     FlutterError.reportError
#23     _reportException
#24     ComponentElement.performRebuild
#25     StatefulElement.performRebuild
#26     Element.rebuild
#27     ComponentElement._firstBuild
#28     StatefulElement._firstBuild
#29     ComponentElement.mount
#30     Element.inflateWidget
#31     MultiChildRenderObjectElement.inflateWidget
#32     MultiChildRenderObjectElement.mount
...     Normal element mounting (7 frames)
#39     _UncontrolledProviderScopeElement.mount
...     Normal element mounting (17 frames)
#56     Element.inflateWidget
#57     Element.updateChild
#58     SingleChildRenderObjectElement.update
#59     Element.updateChild
#60     ComponentElement.performRebuild
#61     Element.rebuild
#62     StatelessElement.update
#63     Element.updateChild
#64     SingleChildRenderObjectElement.update
#65     Element.updateChild
#66     SingleChildRenderObjectElement.update
#67     Element.updateChild
#68     ComponentElement.performRebuild
#69     StatefulElement.performRebuild
#70     Element.rebuild
#71     StatefulElement.update
#72     Element.updateChild
#73     ComponentElement.performRebuild
#74     StatefulElement.performRebuild
#75     Element.rebuild
#76     StatefulElement.update
#77     Element.updateChild
#78     SingleChildRenderObjectElement.update
#79     Element.updateChild
#80     ComponentElement.performRebuild
#81     Element.rebuild
#82     ProxyElement.update
#83     _InheritedNotifierElement.update
#84     Element.updateChild
#85     SingleChildRenderObjectElement.update
#86     Element.updateChild
#87     ComponentElement.performRebuild
#88     StatefulElement.performRebuild
#89     Element.rebuild
#90     StatefulElement.update
#91     Element.updateChild
#92     ComponentElement.performRebuild
#93     Element.rebuild
#94     ProxyElement.update
#95     Element.updateChild
#96     ComponentElement.performRebuild
#97     Element.rebuild
#98     ProxyElement.update
#99     Element.updateChild
#100    ComponentElement.performRebuild
#101    StatefulElement.performRebuild
#102    Element.rebuild
#103    StatefulElement.update
#104    Element.updateChild
#105    ComponentElement.performRebuild
#106    Element.rebuild
#107    StatelessElement.update
#108    Element.updateChild
#109    ComponentElement.performRebuild
#110    Element.rebuild
#111    StatelessElement.update
#112    Element.updateChild
#113    SingleChildRenderObjectElement.update
#114    Element.updateChild
#115    ComponentElement.performRebuild
#116    Element.rebuild
#117    ProxyElement.update
#118    Element.updateChild
#119    ComponentElement.performRebuild
#120    Element.rebuild
#121    ProxyElement.update
#122    Element.updateChild
#123    ComponentElement.performRebuild
#124    StatefulElement.performRebuild
#125    Element.rebuild
#126    StatefulElement.update
#127    Element.updateChild
#128    ComponentElement.performRebuild
#129    StatefulElement.performRebuild
#130    Element.rebuild
#131    StatefulElement.update
#132    Element.updateChild
#133    ComponentElement.performRebuild
#134    StatefulElement.performRebuild
#135    Element.rebuild
#136    BuildOwner.buildScope
#137    WidgetsBinding.drawFrame
#138    RendererBinding._handlePersistentFrameCallback
#139    SchedulerBinding._invokeFrameCallback
#140    SchedulerBinding.handleDrawFrame
#141    SchedulerBinding._handleDrawFrame
#142    _invoke (dart:ui/hooks.dart:145:13)
#143    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338:5)
#144    _drawFrame (dart:ui/hooks.dart:112:31)
(elided 2 frames from class _AssertionError)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4692 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was
ProviderScope
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4692 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was
FirstImplPage
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4692 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was
Scaffold
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4692 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was
Scaffold
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4692 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was
Scaffold
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4692 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was
Scaffold
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4692 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was
Scaffold
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4692 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was
Scaffold
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4692 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was
Scaffold
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4692 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was
Scaffold
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4692 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was
Scaffold
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4692 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was
Scaffold
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4692 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was
Scaffold
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4692 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was
Scaffold
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4692 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was
Scaffold
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4692 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was
Scaffold
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4692 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was
Scaffold
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4692 pos 14: 'owner!._debugCurrentBuildTarget == this': is not true.
The relevant error-causing widget was
Scaffold
════════════════════════════════════════════════════════════════════════════════
flutter: disposing SecondImplNotifier
flutter: onCancel second

```

</details>

am I doing something stupidly wrong? with removal of overrideWithValue its harder to achieve this kind of behavior in a simple way I hope you can manage to bring it back sooner
thanks for your amazing work

**Comment by rrousselGit** [comment]
Oh, I see what's happening.

StateNotifierProviders should always create a new StateNotifier within their ref function, as when the provider is invalidated, they will dispose of the notifier.  
You didn't create a new notifier but instead reused an existing one. Hence the issue

Not much I can do here. I'd make a lint rule for this, but it's very complex to do in this case, and Notifier/AsyncNotifier is the way to go nowadays.
