### ISSUE TITLE
Error with riverpod_lint - Bad state: Too many elements

### ISSUE THREAD

**Issue by redDwarf03** [rrousselGit/riverpod#2194]
**Describe the bug**
When i executed ``dart run custom_lint``, i have some recommendations (normal... i fixed it) but 2 errors:

```

Building package executable... (2.9s)
Built custom_lint:custom_lint.
Plugin provider_parameters threw while analyzing /Users/SSe/SSe/app/ARCHETHIC/archethic_wallet/lib/application/settings/primary_currency.dart:
Bad state: Too many elements
#0      List.single (dart:core-patch/growable_array.dart:354:5)
#1      LegacyProviderDeclarationElement.parse.<anonymous closure> (package:riverpod_analyzer_utils/src/riverpod_element.dart:189:45)
#2      _extension#0.putIfAbsent (package:riverpod_analyzer_utils/src/riverpod_element.dart:337:42)
#3      LegacyProviderDeclarationElement.parse (package:riverpod_analyzer_utils/src/riverpod_element.dart:175:19)
#4      ProviderListenableExpression.parse.parseExpression (package:riverpod_analyzer_utils/src/riverpod_ast.dart:462:50)
#5      ProviderListenableExpression.parse.parseExpression (package:riverpod_analyzer_utils/src/riverpod_ast.dart:470:9)
#6      ProviderListenableExpression.parse (package:riverpod_analyzer_utils/src/riverpod_ast.dart:490:5)
#7      RefWatchInvocation._parse (package:riverpod_analyzer_utils/src/riverpod_ast.dart:349:71)
#8      RefInvocation.parse (package:riverpod_analyzer_utils/src/riverpod_ast.dart:304:45)
#9      RiverpodRegistry._addRefVisitor.<anonymous closure> (package:riverpod_analyzer_utils/src/riverpod_visitor.dart:319:59)
#10     _rootRunUnary (dart:async/zone.dart:1414:13)
#11     _CustomZone.runUnary (dart:async/zone.dart:1307:19)
#12     LinterVisitor._runSubscriptions (package:custom_lint_core/src/node_lint_visitor.dart:1034:27)
#13     LinterVisitor.visitMethodInvocation (package:custom_lint_core/src/node_lint_visitor.dart:603:5)
#14     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:8906:50)
#15     VariableDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:13700:19)
#16     LinterVisitor.visitVariableDeclaration (package:custom_lint_core/src/node_lint_visitor.dart:974:10)
#17     VariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:13695:50)
#18     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:9445:20)
#19     VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:13794:16)
#20     LinterVisitor.visitVariableDeclarationList (package:custom_lint_core/src/node_lint_visitor.dart:980:10)
#21     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:13788:15)
#22     VariableDeclarationStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:13844:19)
#23     LinterVisitor.visitVariableDeclarationStatement (package:custom_lint_core/src/node_lint_visitor.dart:986:10)
#24     VariableDeclarationStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:13840:15)
#25     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:9445:20)
#26     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1333:17)
#27     LinterVisitor.visitBlock (package:custom_lint_core/src/node_lint_visitor.dart:106:10)
#28     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1329:50)
#29     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1284:12)
#30     LinterVisitor.visitBlockFunctionBody (package:custom_lint_core/src/node_lint_visitor.dart:112:10)
#31     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1276:50)
#32     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6102:11)
#33     LinterVisitor.visitFunctionExpression (package:custom_lint_core/src/node_lint_visitor.dart:418:10)
#34     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6091:50)
#35     FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5963:25)
#36     LinterVisitor.visitFunctionDeclaration (package:custom_lint_core/src/node_lint_visitor.dart:406:10)
#37     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:5957:50)
#38     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:9445:20)
#39     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2596:21)
#40     LinterVisitor.visitCompilationUnit (package:custom_lint_core/src/node_lint_visitor.dart:184:10)
#41     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2589:50)
#42     DartLintRule.startUp.<anonymous closure> (package:custom_lint_core/src/lint_rule.dart:125:17)
#43     _rootRun (dart:async/zone.dart:1398:13)
#44     _CustomZone.run (dart:async/zone.dart:1300:19)
#45     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1232:23)
#46     runPostRunCallbacks (package:custom_lint_core/src/plugin_base.dart:14:19)
#47     _ClientAnalyzerPlugin.analyzeFile.<anonymous closure> (package:custom_lint_builder/src/client.dart:772:7)
<asynchronous suspension>
#48     _ClientAnalyzerPlugin._runOperation (package:custom_lint_builder/src/client.dart:815:14)
<asynchronous suspension>
#49     _ClientAnalyzerPlugin.analyzeFile (package:custom_lint_builder/src/client.dart:740:5)
<asynchronous suspension>
#50     ServerPlugin.analyzeFiles (package:analyzer_plugin/plugin/plugin.dart:119:7)
<asynchronous suspension>
#51     ServerPlugin.afterNewContextCollection.<anonymous closure> (package:analyzer_plugin/plugin/plugin.dart:86:7)
<asynchronous suspension>
#52     ServerPlugin._forAnalysisContexts (package:analyzer_plugin/plugin/plugin.dart:525:7)
<asynchronous suspension>
#53     ServerPlugin.afterNewContextCollection (package:analyzer_plugin/plugin/plugin.dart:84:5)
<asynchronous suspension>
#54     _ClientAnalyzerPlugin._runOperation (package:custom_lint_builder/src/client.dart:815:14)
<asynchronous suspension>
#55     ServerPlugin.handleAnalysisSetContextRoots (package:analyzer_plugin/plugin/plugin.dart:273:5)
<asynchronous suspension>
#56     _ClientAnalyzerPlugin._runOperation (package:custom_lint_builder/src/client.dart:815:14)
<asynchronous suspension>
#57     ServerPlugin._getResponse (package:analyzer_plugin/plugin/plugin.dart:544:18)
<asynchronous suspension>
#58     ServerPlugin._onRequest (package:analyzer_plugin/plugin/plugin.dart:611:18)
<asynchronous suspension>

Plugin provider_parameters threw while analyzing /Users/SSe/SSe/app/ARCHETHIC/archethic_wallet/lib/application/nft/nft_category.dart:
Bad state: Too many elements
#0      List.single (dart:core-patch/growable_array.dart:354:5)
#1      LegacyProviderDeclarationElement.parse.<anonymous closure> (package:riverpod_analyzer_utils/src/riverpod_element.dart:189:45)
#2      _extension#0.putIfAbsent (package:riverpod_analyzer_utils/src/riverpod_element.dart:337:42)
#3      LegacyProviderDeclarationElement.parse (package:riverpod_analyzer_utils/src/riverpod_element.dart:175:19)
#4      ProviderListenableExpression.parse.parseExpression (package:riverpod_analyzer_utils/src/riverpod_ast.dart:462:50)
#5      ProviderListenableExpression.parse.parseExpression (package:riverpod_analyzer_utils/src/riverpod_ast.dart:470:9)
#6      ProviderListenableExpression.parse (package:riverpod_analyzer_utils/src/riverpod_ast.dart:490:5)
#7      RefWatchInvocation._parse (package:riverpod_analyzer_utils/src/riverpod_ast.dart:349:71)
#8      RefInvocation.parse (package:riverpod_analyzer_utils/src/riverpod_ast.dart:304:45)
#9      RiverpodRegistry._addRefVisitor.<anonymous closure> (package:riverpod_analyzer_utils/src/riverpod_visitor.dart:319:59)
#10     _rootRunUnary (dart:async/zone.dart:1414:13)
#11     _CustomZone.runUnary (dart:async/zone.dart:1307:19)
#12     LinterVisitor._runSubscriptions (package:custom_lint_core/src/node_lint_visitor.dart:1034:27)
#13     LinterVisitor.visitMethodInvocation (package:custom_lint_core/src/node_lint_visitor.dart:603:5)
#14     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:8906:50)
#15     ReturnStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:11327:18)
#16     LinterVisitor.visitReturnStatement (package:custom_lint_core/src/node_lint_visitor.dart:812:10)
#17     ReturnStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:11323:50)
#18     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:9445:20)
#19     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1333:17)
#20     LinterVisitor.visitBlock (package:custom_lint_core/src/node_lint_visitor.dart:106:10)
#21     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1329:50)
#22     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1284:12)
#23     LinterVisitor.visitBlockFunctionBody (package:custom_lint_core/src/node_lint_visitor.dart:112:10)
#24     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1276:50)
#25     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6102:11)
#26     LinterVisitor.visitFunctionExpression (package:custom_lint_core/src/node_lint_visitor.dart:418:10)
#27     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6091:50)
#28     FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5963:25)
#29     LinterVisitor.visitFunctionDeclaration (package:custom_lint_core/src/node_lint_visitor.dart:406:10)
#30     FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:5957:50)
#31     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:9445:20)
#32     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2596:21)
#33     LinterVisitor.visitCompilationUnit (package:custom_lint_core/src/node_lint_visitor.dart:184:10)
#34     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2589:50)
#35     DartLintRule.startUp.<anonymous closure> (package:custom_lint_core/src/lint_rule.dart:125:17)
#36     _rootRun (dart:async/zone.dart:1398:13)
#37     _CustomZone.run (dart:async/zone.dart:1300:19)
#38     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1232:23)
#39     runPostRunCallbacks (package:custom_lint_core/src/plugin_base.dart:14:19)
#40     _ClientAnalyzerPlugin.analyzeFile.<anonymous closure> (package:custom_lint_builder/src/client.dart:772:7)
<asynchronous suspension>
#41     _ClientAnalyzerPlugin._runOperation (package:custom_lint_builder/src/client.dart:815:14)
<asynchronous suspension>
#42     _ClientAnalyzerPlugin.analyzeFile (package:custom_lint_builder/src/client.dart:740:5)
<asynchronous suspension>
#43     ServerPlugin.analyzeFiles (package:analyzer_plugin/plugin/plugin.dart:119:7)
<asynchronous suspension>
#44     ServerPlugin.afterNewContextCollection.<anonymous closure> (package:analyzer_plugin/plugin/plugin.dart:86:7)
<asynchronous suspension>
#45     ServerPlugin._forAnalysisContexts (package:analyzer_plugin/plugin/plugin.dart:525:7)
<asynchronous suspension>
#46     ServerPlugin.afterNewContextCollection (package:analyzer_plugin/plugin/plugin.dart:84:5)
<asynchronous suspension>
#47     _ClientAnalyzerPlugin._runOperation (package:custom_lint_builder/src/client.dart:815:14)
<asynchronous suspension>
#48     ServerPlugin.handleAnalysisSetContextRoots (package:analyzer_plugin/plugin/plugin.dart:273:5)
<asynchronous suspension>
#49     _ClientAnalyzerPlugin._runOperation (package:custom_lint_builder/src/client.dart:815:14)
<asynchronous suspension>
#50     ServerPlugin._getResponse (package:analyzer_plugin/plugin/plugin.dart:544:18)
<asynchronous suspension>
#51     ServerPlugin._onRequest (package:analyzer_plugin/plugin/plugin.dart:611:18)
<asynchronous suspension>

```

**To Reproduce**

It concerns these 2 files:

- https://github.com/archethic-foundation/archethic-wallet/blob/dev/lib/application/nft/nft_category.dart 
- https://github.com/archethic-foundation/archethic-wallet/blob/dev/lib/application/settings/primary_currency.dart

i have a dedicated PR for riverpod lint integration: https://github.com/archethic-foundation/archethic-wallet/pull/677

**Expected behavior**
no error ``A lint plugin threw an exception``

**Comment by redDwarf03** [comment]
another issue is: if I have many notifiers in many files link with ``part`` and ``part of`` , i have some errors [type_argument_not_matching_bounds](https://dart.dev/diagnostics/type_argument_not_matching_bounds)

**Comment by kittz** [comment]
I have same problem: #2182
