### ISSUE TITLE
type 'SimpleIdentifierImpl' is not a subtype of type 'PropertyAccess' in type cast

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/riverpod#2294]
https://github.com/invertase/dart_custom_lint/issues/113

**Describe the bug**
When the dart analyzer is started, I get an error in custom_lint.log.

EDIT: I am on 0.3.2 of `custom_lint`.

```
The Dart VM service is listening on http://127.0.0.1:1421/dKDOdS3hIVo=/
The Dart DevTools debugger and profiler is available at: http://127.0.0.1:1421/dKDOdS3hIVo=/devtools/#/?uri=ws%3A%2F%2F127.0.0.1%3A1421%2FdKDOdS3hIVo%3D%2Fws
[stateless_ref] 2023-03-09T10:51:32.424472 Plugin stateless_ref threw while analyzing C:\dev\trnv2_mobile_app\lib\areas\destiny-2\ui\profile\widgets\playlist_builder.dart:
[stateless_ref] 2023-03-09T10:51:32.424472 type 'SimpleIdentifierImpl' is not a subtype of type 'PropertyAccess' in type cast
[stateless_ref] 2023-03-09T10:51:32.424472 #0      LegacyProviderDeclaration._parse (package:riverpod_analyzer_utils/src/riverpod_ast/legacy_provider_declaration.dart:149:45)
[stateless_ref] 2023-03-09T10:51:32.424472 #1      _ParseRiverpodUnitVisitor.visitVariableDeclaration (package:riverpod_analyzer_utils/src/riverpod_ast/resolve_riverpod.dart:240:51)
[stateless_ref] 2023-03-09T10:51:32.424472 #2      VariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:13975:50)
[stateless_ref] 2023-03-09T10:51:32.424472 #3      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:9626:20)
[stateless_ref] 2023-03-09T10:51:32.424472 #4      VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:14074:16)
[stateless_ref] 2023-03-09T10:51:32.424472 #5      RecursiveAstVisitor.visitVariableDeclarationList (package:analyzer/dart/ast/visitor.dart:1739:10)
[stateless_ref] 2023-03-09T10:51:32.424472 #6      VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:14068:15)
[stateless_ref] 2023-03-09T10:51:32.424472 #7      VariableDeclarationStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:14124:19)
[stateless_ref] 2023-03-09T10:51:32.424472 #8      RecursiveAstVisitor.visitVariableDeclarationStatement (package:analyzer/dart/ast/visitor.dart:1745:10)
[stateless_ref] 2023-03-09T10:51:32.424472 #9      VariableDeclarationStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:14120:15)
[stateless_ref] 2023-03-09T10:51:32.424472 #10     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:9626:20)
[stateless_ref] 2023-03-09T10:51:32.424472 #11     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1260:17)
[stateless_ref] 2023-03-09T10:51:32.424472 #12     RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:847:10)
[stateless_ref] 2023-03-09T10:51:32.424472 #13     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1256:50)
[stateless_ref] 2023-03-09T10:51:32.424472 #14     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1211:12)
[stateless_ref] 2023-03-09T10:51:32.424472 #15     RecursiveAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:853:10)
[stateless_ref] 2023-03-09T10:51:32.424472 #16     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1203:50)
[stateless_ref] 2023-03-09T10:51:32.424472 #17     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:8918:11)
[stateless_ref] 2023-03-09T10:51:32.424472 #18     RecursiveAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:1357:10)
[stateless_ref] 2023-03-09T10:51:32.424472 #19     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:8910:50)
[stateless_ref] 2023-03-09T10:51:32.424472 #20     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:9626:20)
[stateless_ref] 2023-03-09T10:51:32.424472 #21     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2050:13)
[stateless_ref] 2023-03-09T10:51:32.424472 #22     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:901:10)
[stateless_ref] 2023-03-09T10:51:32.424472 #23     _ParseRiverpodUnitVisitor.visitClassDeclaration (package:riverpod_analyzer_utils/src/riverpod_ast/resolve_riverpod.dart:222:11)
[stateless_ref] 2023-03-09T10:51:32.424472 #24     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2040:50)
[stateless_ref] 2023-03-09T10:51:32.424472 #25     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:9626:20)
[stateless_ref] 2023-03-09T10:51:32.424472 #26     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2585:21)
[stateless_ref] 2023-03-09T10:51:32.424472 #27     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:925:10)
[stateless_ref] 2023-03-09T10:51:32.424472 #28     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2578:50)
[stateless_ref] 2023-03-09T10:51:32.424472 #29     new ResolvedRiverpodLibraryResult.from (package:riverpod_analyzer_utils/src/riverpod_ast/resolve_riverpod.dart:16:19)
[stateless_ref] 2023-03-09T10:51:32.424472 #30     _ParseRiverpod._setupRiverpod (package:riverpod_lint/src/riverpod_custom_lint.dart:90:50)
[stateless_ref] 2023-03-09T10:51:32.424472 <asynchronous suspension>
[stateless_ref] 2023-03-09T10:51:32.424472 #31     RiverpodLintRule.startUp (package:riverpod_lint/src/riverpod_custom_lint.dart:62:5)
[stateless_ref] 2023-03-09T10:51:32.424472 <asynchronous suspension>
[stateless_ref] 2023-03-09T10:51:32.424472 #32     _ClientAnalyzerPlugin._startUpLintRule (package:custom_lint_builder/src/client.dart:877:5)
[stateless_ref] 2023-03-09T10:51:32.424472 <asynchronous suspension>
[stateless_ref] 2023-03-09T10:51:32.424472 #33     Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
[stateless_ref] 2023-03-09T10:51:32.424472 <asynchronous suspension>
[stateless_ref] 2023-03-09T10:51:32.424472 #34     _ClientAnalyzerPlugin.analyzeFile.<anonymous closure> (package:custom_lint_builder/src/client.dart:753:7)
[stateless_ref] 2023-03-09T10:51:32.424472 <asynchronous suspension>
[stateless_ref] 2023-03-09T10:51:32.424472 #35     _ClientAnalyzerPlugin._runOperation (package:custom_lint_builder/src/client.dart:822:14)
[stateless_ref] 2023-03-09T10:51:32.424472 <asynchronous suspension>
[stateless_ref] 2023-03-09T10:51:32.424472 #36     _ClientAnalyzerPlugin.analyzeFile (package:custom_lint_builder/src/client.dart:747:5)
[stateless_ref] 2023-03-09T10:51:32.424472 <asynchronous suspension>
[stateless_ref] 2023-03-09T10:51:32.424472 #37     ServerPlugin.analyzeFiles (package:analyzer_plugin/plugin/plugin.dart:119:7)
[stateless_ref] 2023-03-09T10:51:32.424472 <asynchronous suspension>
[stateless_ref] 2023-03-09T10:51:32.424472 #38     ServerPlugin.afterNewContextCollection.<anonymous closure> (package:analyzer_plugin/plugin/plugin.dart:86:7)
[stateless_ref] 2023-03-09T10:51:32.424472 <asynchronous suspension>
[stateless_ref] 2023-03-09T10:51:32.424472 #39     ServerPlugin._forAnalysisContexts (package:analyzer_plugin/plugin/plugin.dart:518:9)
[stateless_ref] 2023-03-09T10:51:32.424472 <asynchronous suspension>
[stateless_ref] 2023-03-09T10:51:32.424472 #40     ServerPlugin.afterNewContextCollection (package:analyzer_plugin/plugin/plugin.dart:84:5)
[stateless_ref] 2023-03-09T10:51:32.424472 <asynchronous suspension>
[stateless_ref] 2023-03-09T10:51:32.424472 #41     _ClientAnalyzerPlugin._runOperation (package:custom_lint_builder/src/client.dart:822:14)
[stateless_ref] 2023-03-09T10:51:32.424472 <asynchronous suspension>
[stateless_ref] 2023-03-09T10:51:32.424472 #42     ServerPlugin.handleAnalysisSetContextRoots (package:analyzer_plugin/plugin/plugin.dart:273:5)
[stateless_ref] 2023-03-09T10:51:32.424472 <asynchronous suspension>
[stateless_ref] 2023-03-09T10:51:32.424472 #43     _ClientAnalyzerPlugin._runOperation (package:custom_lint_builder/src/client.dart:822:14)
[stateless_ref] 2023-03-09T10:51:32.424472 <asynchronous suspension>
[stateless_ref] 2023-03-09T10:51:32.424472 #44     ServerPlugin._getResponse (package:analyzer_plugin/plugin/plugin.dart:544:18)
[stateless_ref] 2023-03-09T10:51:32.424472 <asynchronous suspension>
[stateless_ref] 2023-03-09T10:51:32.424472 #45     ServerPlugin._onRequest (package:analyzer_plugin/plugin/plugin.dart:611:18)
[stateless_ref] 2023-03-09T10:51:32.424472 <asynchronous suspension>
[stateless_ref] 2023-03-09T10:51:32.424472
```

**To Reproduce**

Unknown

**Expected behavior**
I should be getting analyzer errors from custom_lint.

**Comment by rrousselGit** [comment]
cc @Reprevise

**Comment by rrousselGit** [comment]
@Reprevise could you possibly share the code that triggered this error?

**Comment by Reprevise** [comment]
Hey there @rrousselGit, the file is decently large, not sure what line specifically is causing the error. I'm not declaring any new providers in this file, just referencing others declared in other files.

**Comment by rrousselGit** [comment]
It'd still be really helpful to see it though

**Comment by Reprevise** [comment]
Removed some unnecessary bits

<details>
<summary>Code</summary>

```dart
class D2PlaylistBuilder extends ConsumerWidget {
  const D2PlaylistBuilder();

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final playlist = ref.watch(
      fetchSegmentsProvider(
        FetchSegmentsParams(
          type: 'playlist',
          queryParameters: {
            'season': selectedSeason < 1 ? currentSeason : selectedSeason,
          }.lockUnsafe,
        ),
      ),
    );

    final playlistProvider =
        selectedPlaylistProvider(platformInfo.platformUserHandle!);
    final seasonProvider =
        selectedSeasonProvider(platformInfo.platformUserHandle!);
    final selectedPlaylist = ref.watch(playlistProvider);

    ref.listen<int?>(seasonProvider, (_, value) {
      ref.read(playlistProvider.notifier).state = const D2PlaylistInfo();
    });

    return playlist.defaultWhen(
      loading: () => const Center(child: MyCircularProgressIndicator()),
      error: (error, _) => Center(child: MyErrorWidget(error: error)),
      data: (playlistData) {
        WidgetsBinding.instance.addPostFrameCallback((_) {
          if (selectedPlaylist.playlistName == null &&
              playlistData.isNotEmpty) {
            ref.read(playlistProvider.notifier).state = D2PlaylistInfo(
              playlistName: playlistData.first.attributes['playlist'],
            );
          }
        });

        return Column(
          children: [
            PlaylistCardBuilder(
              playlists: playlistData.map((e) {
                final elo = e.stats['elo']!;

                return PlaylistItem(
                  name: e.metadata['name'],
                  rankValueText: formatStat(elo),
                  emblemUrl: (elo.metadata['iconUrl'] as Map?)?['value'],
                  ldbRank: elo.rank,
                  percentile: elo.percentile,
                );
              }).toList(),
              onPageChanged: (page) {
                ref.read(playlistProvider.notifier).state = D2PlaylistInfo(
                  playlistIndex: page,
                  playlistName: playlistData[page].attributes['playlist'],
                );
              },
            ),
            _buildDPlaylistStats(
              // ..
            ),
          ],
        );
      },
    );
  }

  Widget _buildDPlaylistStats(
    // ..
  ) {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 16),
      child: Column(
        children: [
          Padding(
            padding: const EdgeInsets.only(bottom: 12),
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                // ..
                Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Consumer(
                      builder: (context, ref, child) {
                        final trialData = ref.watch(
                          fetchD2TrialsStatsByPlatformInfo(platformInfo),
                        );
                        const TextStyle style = TextStyle(
                          fontSize: 16,
                          fontWeight: FontWeight.bold,
                        );

                        return trialData.customWhen(
                          data: (value) => Row(
                            children: [
                              Text(
                                '${value.currentStreak} ',
                                style: style,
                              ),
                              if (value.currentStreak > 0)
                                const Icon(
                                  Icons.local_fire_department,
                                  color: kcFlameOrage,
                                  size: 14,
                                ),
                            ],
                          ),
                          loading: () => const SizedBox(height: 19),
                          error: (_) => const Text('-', style: style),
                        );
                      },
                    ),
                  ],
                ),
                const Spacer(flex: 3),
                Consumer(
                  builder: (context, ref, child) => GestureDetector(
                    onTap: () {
                      ref.read(d2trialsPlatformInfoProvider.notifier).state =
                          platformInfo;
                      ref.read(trialsLookupStateProvider.notifier).state =
                          TrialsLookupState.results;
                      context.tabsRouter.navigate(const TrialsRouter());
                    },
                    child: Text(
                      'View Fireteam'.hardcoded,
                      style: const TextStyle(
                        fontSize: 14,
                        color: kcTextSecondary,
                        fontWeight: FontWeight.w500,
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

class _StatsSection extends StatelessWidget {
  const _StatsSection();

  @override
  Widget build(BuildContext context) {
    final i10n = TrnLocalizations.of(context);

    final trialsStatsProvider = fetchD2TrialsStatsByPlatformInfo(_platformInfo);

    return Consumer(
      builder: (context, ref, child) {
        final trialData = ref.watch(trialsStatsProvider);
        return trialData.customWhen(
          data: (value) {
            // ..
          },
          loading: () => child!,
          error: (error) => MyErrorWidget(
            error: error,
            onTryAgain: () {
              ref.invalidate(trialsStatsProvider);
              ref.read(trialsStatsProvider.future);
            },
          ),
        );
      },
    );
  }
}
```
</details>

**Comment by Reprevise** [comment]
Hey @rrousselGit, unfortunately the issue is still not fixed after the release of riverpod_analyzer_utils 0.1.4.

Here's the log:

```
[stateless_ref] 2023-03-10T13:27:44.227765 Plugin stateless_ref threw while analyzing C:\dev\trnv2_mobile_app\lib\areas\destiny-2\ui\profile\widgets\playlist_builder.dart:
[stateless_ref] 2023-03-10T13:27:44.227765 type 'SimpleIdentifierImpl' is not a subtype of type 'PropertyAccess' in type cast
[stateless_ref] 2023-03-10T13:27:44.227765 #0      LegacyProviderDeclaration._parse (package:riverpod_analyzer_utils/src/riverpod_ast/legacy_provider_declaration.dart:149:45)
[stateless_ref] 2023-03-10T13:27:44.227765 #1      _ParseRiverpodUnitVisitor.visitVariableDeclaration (package:riverpod_analyzer_utils/src/riverpod_ast/resolve_riverpod.dart:240:51)
[stateless_ref] 2023-03-10T13:27:44.227765 #2      VariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:13975:50)
[stateless_ref] 2023-03-10T13:27:44.227765 #3      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:9626:20)
[stateless_ref] 2023-03-10T13:27:44.227765 #4      VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:14074:16)
[stateless_ref] 2023-03-10T13:27:44.227765 #5      RecursiveAstVisitor.visitVariableDeclarationList (package:analyzer/dart/ast/visitor.dart:1739:10)
[stateless_ref] 2023-03-10T13:27:44.227765 #6      VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:14068:15)
[stateless_ref] 2023-03-10T13:27:44.227765 #7      VariableDeclarationStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:14124:19)
[stateless_ref] 2023-03-10T13:27:44.227765 #8      RecursiveAstVisitor.visitVariableDeclarationStatement (package:analyzer/dart/ast/visitor.dart:1745:10)
[stateless_ref] 2023-03-10T13:27:44.227765 #9      VariableDeclarationStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:14120:15)
[stateless_ref] 2023-03-10T13:27:44.227765 #10     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:9626:20)
[stateless_ref] 2023-03-10T13:27:44.227765 #11     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1260:17)
[stateless_ref] 2023-03-10T13:27:44.227765 #12     RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:847:10)
[stateless_ref] 2023-03-10T13:27:44.227765 #13     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1256:50)
[stateless_ref] 2023-03-10T13:27:44.227765 #14     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1211:12)
[stateless_ref] 2023-03-10T13:27:44.227765 #15     RecursiveAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:853:10)
[stateless_ref] 2023-03-10T13:27:44.227765 #16     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1203:50)
[stateless_ref] 2023-03-10T13:27:44.227765 #17     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:8918:11)
[stateless_ref] 2023-03-10T13:27:44.227765 #18     RecursiveAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:1357:10)
[stateless_ref] 2023-03-10T13:27:44.227765 #19     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:8910:50)
[stateless_ref] 2023-03-10T13:27:44.227765 #20     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:9626:20)
[stateless_ref] 2023-03-10T13:27:44.227765 #21     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2050:13)
[stateless_ref] 2023-03-10T13:27:44.227765 #22     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:901:10)
[stateless_ref] 2023-03-10T13:27:44.227765 #23     _ParseRiverpodUnitVisitor.visitClassDeclaration (package:riverpod_analyzer_utils/src/riverpod_ast/resolve_riverpod.dart:222:11)
[stateless_ref] 2023-03-10T13:27:44.227765 #24     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2040:50)
[stateless_ref] 2023-03-10T13:27:44.227765 #25     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:9626:20)
[stateless_ref] 2023-03-10T13:27:44.227765 #26     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2585:21)
[stateless_ref] 2023-03-10T13:27:44.227765 #27     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:925:10)
[stateless_ref] 2023-03-10T13:27:44.227765 #28     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2578:50)
[stateless_ref] 2023-03-10T13:27:44.227765 #29     new ResolvedRiverpodLibraryResult.from (package:riverpod_analyzer_utils/src/riverpod_ast/resolve_riverpod.dart:16:14)
[stateless_ref] 2023-03-10T13:27:44.227765 #30     _ParseRiverpod._setupRiverpod (package:riverpod_lint/src/riverpod_custom_lint.dart:90:50)
[stateless_ref] 2023-03-10T13:27:44.227765 <asynchronous suspension>
[stateless_ref] 2023-03-10T13:27:44.227765 #31     RiverpodLintRule.startUp (package:riverpod_lint/src/riverpod_custom_lint.dart:62:5)
[stateless_ref] 2023-03-10T13:27:44.227765 <asynchronous suspension>
[stateless_ref] 2023-03-10T13:27:44.227765 #32     _ClientAnalyzerPlugin._startUpLintRule (package:custom_lint_builder/src/client.dart:877:5)
[stateless_ref] 2023-03-10T13:27:44.227765 <asynchronous suspension>
[stateless_ref] 2023-03-10T13:27:44.227765 #33     Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
[stateless_ref] 2023-03-10T13:27:44.227765 <asynchronous suspension>
[stateless_ref] 2023-03-10T13:27:44.227765 #34     _ClientAnalyzerPlugin.analyzeFile.<anonymous closure> (package:custom_lint_builder/src/client.dart:753:7)
[stateless_ref] 2023-03-10T13:27:44.227765 <asynchronous suspension>
[stateless_ref] 2023-03-10T13:27:44.227765 #35     _ClientAnalyzerPlugin._runOperation (package:custom_lint_builder/src/client.dart:822:14)
[stateless_ref] 2023-03-10T13:27:44.227765 <asynchronous suspension>
[stateless_ref] 2023-03-10T13:27:44.227765 #36     _ClientAnalyzerPlugin.analyzeFile (package:custom_lint_builder/src/client.dart:747:5)
[stateless_ref] 2023-03-10T13:27:44.227765 <asynchronous suspension>
[stateless_ref] 2023-03-10T13:27:44.227765 #37     ServerPlugin.analyzeFiles (package:analyzer_plugin/plugin/plugin.dart:119:7)
[stateless_ref] 2023-03-10T13:27:44.227765 <asynchronous suspension>
[stateless_ref] 2023-03-10T13:27:44.227765 #38     ServerPlugin.afterNewContextCollection.<anonymous closure> (package:analyzer_plugin/plugin/plugin.dart:86:7)
[stateless_ref] 2023-03-10T13:27:44.227765 <asynchronous suspension>
[stateless_ref] 2023-03-10T13:27:44.227765 #39     ServerPlugin._forAnalysisContexts (package:analyzer_plugin/plugin/plugin.dart:518:9)
[stateless_ref] 2023-03-10T13:27:44.227765 <asynchronous suspension>
[stateless_ref] 2023-03-10T13:27:44.227765 #40     ServerPlugin.afterNewContextCollection (package:analyzer_plugin/plugin/plugin.dart:84:5)
[stateless_ref] 2023-03-10T13:27:44.227765 <asynchronous suspension>
[stateless_ref] 2023-03-10T13:27:44.227765 #41     _ClientAnalyzerPlugin._runOperation (package:custom_lint_builder/src/client.dart:822:14)
[stateless_ref] 2023-03-10T13:27:44.227765 <asynchronous suspension>
[stateless_ref] 2023-03-10T13:27:44.227765 #42     ServerPlugin.handleAnalysisSetContextRoots (package:analyzer_plugin/plugin/plugin.dart:273:5)
[stateless_ref] 2023-03-10T13:27:44.227765 <asynchronous suspension>
[stateless_ref] 2023-03-10T13:27:44.227765 #43     _ClientAnalyzerPlugin._runOperation (package:custom_lint_builder/src/client.dart:822:14)
[stateless_ref] 2023-03-10T13:27:44.227765 <asynchronous suspension>
[stateless_ref] 2023-03-10T13:27:44.227765 #44     ServerPlugin._getResponse (package:analyzer_plugin/plugin/plugin.dart:544:18)
[stateless_ref] 2023-03-10T13:27:44.227765 <asynchronous suspension>
[stateless_ref] 2023-03-10T13:27:44.227765 #45     ServerPlugin._onRequest (package:analyzer_plugin/plugin/plugin.dart:611:18)
[stateless_ref] 2023-03-10T13:27:44.227765 <asynchronous suspension>
[stateless_ref] 2023-03-10T13:27:44.227765
```
