### ISSUE TITLE
type 'SimpleIdentifierImpl' is not a subtype of type 'PropertyAccess' in type cast

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/riverpod#2313]
Hey @rrousselGit, unfortunately the issue is still not fixed after the release of riverpod_analyzer_utils 0.1.4.

Here's the log:

```
[stateless_ref] 2023-03-10T13:27:44.227765 Plugin stateless_ref threw while analyzing C:\dev\trnv2_mobile_app\lib\areas\destiny-2\ui\profile\widgets\playlist_builder.dart:
[stateless_ref] 2023-03-10T13:27:44.227765 type 'SimpleIdentifierImpl' is not a subtype of type 'PropertyAccess' in type cast
[stateless_ref] 2023-03-10T13:27:44.227765 #0      LegacyProviderDeclaration._parse (package:riverpod_analyzer_utils/src/riverpod_ast/legacy_provider_declaration.dart:149:45)
[stateless_ref] 2023-03-10T13:27:44.227765 #1      _ParseRiverpodUnitVisitor.visitVariableDeclaration (package:riverpod_analyzer_utils/src/riverpod_ast/resolve_riverpod.dart:240:51)
[stateless_ref] 2023-03-10T13:27:44.227765 #2      VariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:13975:50)
[stateless_ref] 2023-03-10T13:27:44.227765 #3      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:9626:20)
[stateless_ref] 2023-03-10T13:27:44.227765 #4      VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:14074:16)
[stateless_ref] 2023-03-10T13:27:44.227765 #5      RecursiveAstVisitor.visitVariableDeclarationList (package:analyzer/dart/ast/visitor.dart:1739:10)
[stateless_ref] 2023-03-10T13:27:44.227765 #6      VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:14068:15)
[stateless_ref] 2023-03-10T13:27:44.227765 #7      VariableDeclarationStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:14124:19)
[stateless_ref] 2023-03-10T13:27:44.227765 #8      RecursiveAstVisitor.visitVariableDeclarationStatement (package:analyzer/dart/ast/visitor.dart:1745:10)
[stateless_ref] 2023-03-10T13:27:44.227765 #9      VariableDeclarationStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:14120:15)
[stateless_ref] 2023-03-10T13:27:44.227765 #10     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:9626:20)
[stateless_ref] 2023-03-10T13:27:44.227765 #11     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1260:17)
[stateless_ref] 2023-03-10T13:27:44.227765 #12     RecursiveAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:847:10)
[stateless_ref] 2023-03-10T13:27:44.227765 #13     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1256:50)
[stateless_ref] 2023-03-10T13:27:44.227765 #14     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1211:12)
[stateless_ref] 2023-03-10T13:27:44.227765 #15     RecursiveAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:853:10)
[stateless_ref] 2023-03-10T13:27:44.227765 #16     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1203:50)
[stateless_ref] 2023-03-10T13:27:44.227765 #17     MethodDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:8918:11)
[stateless_ref] 2023-03-10T13:27:44.227765 #18     RecursiveAstVisitor.visitMethodDeclaration (package:analyzer/dart/ast/visitor.dart:1357:10)
[stateless_ref] 2023-03-10T13:27:44.227765 #19     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:8910:50)
[stateless_ref] 2023-03-10T13:27:44.227765 #20     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:9626:20)
[stateless_ref] 2023-03-10T13:27:44.227765 #21     ClassDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2050:13)
[stateless_ref] 2023-03-10T13:27:44.227765 #22     RecursiveAstVisitor.visitClassDeclaration (package:analyzer/dart/ast/visitor.dart:901:10)
[stateless_ref] 2023-03-10T13:27:44.227765 #23     _ParseRiverpodUnitVisitor.visitClassDeclaration (package:riverpod_analyzer_utils/src/riverpod_ast/resolve_riverpod.dart:222:11)
[stateless_ref] 2023-03-10T13:27:44.227765 #24     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2040:50)
[stateless_ref] 2023-03-10T13:27:44.227765 #25     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:9626:20)
[stateless_ref] 2023-03-10T13:27:44.227765 #26     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2585:21)
[stateless_ref] 2023-03-10T13:27:44.227765 #27     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:925:10)
[stateless_ref] 2023-03-10T13:27:44.227765 #28     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2578:50)
[stateless_ref] 2023-03-10T13:27:44.227765 #29     new ResolvedRiverpodLibraryResult.from (package:riverpod_analyzer_utils/src/riverpod_ast/resolve_riverpod.dart:16:14)
[stateless_ref] 2023-03-10T13:27:44.227765 #30     _ParseRiverpod._setupRiverpod (package:riverpod_lint/src/riverpod_custom_lint.dart:90:50)
[stateless_ref] 2023-03-10T13:27:44.227765 <asynchronous suspension>
[stateless_ref] 2023-03-10T13:27:44.227765 #31     RiverpodLintRule.startUp (package:riverpod_lint/src/riverpod_custom_lint.dart:62:5)
[stateless_ref] 2023-03-10T13:27:44.227765 <asynchronous suspension>
[stateless_ref] 2023-03-10T13:27:44.227765 #32     _ClientAnalyzerPlugin._startUpLintRule (package:custom_lint_builder/src/client.dart:877:5)
[stateless_ref] 2023-03-10T13:27:44.227765 <asynchronous suspension>
[stateless_ref] 2023-03-10T13:27:44.227765 #33     Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
[stateless_ref] 2023-03-10T13:27:44.227765 <asynchronous suspension>
[stateless_ref] 2023-03-10T13:27:44.227765 #34     _ClientAnalyzerPlugin.analyzeFile.<anonymous closure> (package:custom_lint_builder/src/client.dart:753:7)
[stateless_ref] 2023-03-10T13:27:44.227765 <asynchronous suspension>
[stateless_ref] 2023-03-10T13:27:44.227765 #35     _ClientAnalyzerPlugin._runOperation (package:custom_lint_builder/src/client.dart:822:14)
[stateless_ref] 2023-03-10T13:27:44.227765 <asynchronous suspension>
[stateless_ref] 2023-03-10T13:27:44.227765 #36     _ClientAnalyzerPlugin.analyzeFile (package:custom_lint_builder/src/client.dart:747:5)
[stateless_ref] 2023-03-10T13:27:44.227765 <asynchronous suspension>
[stateless_ref] 2023-03-10T13:27:44.227765 #37     ServerPlugin.analyzeFiles (package:analyzer_plugin/plugin/plugin.dart:119:7)
[stateless_ref] 2023-03-10T13:27:44.227765 <asynchronous suspension>
[stateless_ref] 2023-03-10T13:27:44.227765 #38     ServerPlugin.afterNewContextCollection.<anonymous closure> (package:analyzer_plugin/plugin/plugin.dart:86:7)
[stateless_ref] 2023-03-10T13:27:44.227765 <asynchronous suspension>
[stateless_ref] 2023-03-10T13:27:44.227765 #39     ServerPlugin._forAnalysisContexts (package:analyzer_plugin/plugin/plugin.dart:518:9)
[stateless_ref] 2023-03-10T13:27:44.227765 <asynchronous suspension>
[stateless_ref] 2023-03-10T13:27:44.227765 #40     ServerPlugin.afterNewContextCollection (package:analyzer_plugin/plugin/plugin.dart:84:5)
[stateless_ref] 2023-03-10T13:27:44.227765 <asynchronous suspension>
[stateless_ref] 2023-03-10T13:27:44.227765 #41     _ClientAnalyzerPlugin._runOperation (package:custom_lint_builder/src/client.dart:822:14)
[stateless_ref] 2023-03-10T13:27:44.227765 <asynchronous suspension>
[stateless_ref] 2023-03-10T13:27:44.227765 #42     ServerPlugin.handleAnalysisSetContextRoots (package:analyzer_plugin/plugin/plugin.dart:273:5)
[stateless_ref] 2023-03-10T13:27:44.227765 <asynchronous suspension>
[stateless_ref] 2023-03-10T13:27:44.227765 #43     _ClientAnalyzerPlugin._runOperation (package:custom_lint_builder/src/client.dart:822:14)
[stateless_ref] 2023-03-10T13:27:44.227765 <asynchronous suspension>
[stateless_ref] 2023-03-10T13:27:44.227765 #44     ServerPlugin._getResponse (package:analyzer_plugin/plugin/plugin.dart:544:18)
[stateless_ref] 2023-03-10T13:27:44.227765 <asynchronous suspension>
[stateless_ref] 2023-03-10T13:27:44.227765 #45     ServerPlugin._onRequest (package:analyzer_plugin/plugin/plugin.dart:611:18)
[stateless_ref] 2023-03-10T13:27:44.227765 <asynchronous suspension>
[stateless_ref] 2023-03-10T13:27:44.227765
```

_Originally posted by @Reprevise in https://github.com/rrousselGit/riverpod/issues/2294#issuecomment-1464219488_

**Comment by rrousselGit** [comment]
@Reprivise Could you share the code that triggered this exception? I'm trying to understand how it happened but fail to do so.

So need for it to work, just paste the raw dart file if you don't mind.
