### ISSUE TITLE
Mocking (AutoDispose)FamilyNotifier breaks widget tests in current stable Flutter version

### ISSUE THREAD

**Issue by Chrisi63** [rrousselGit/riverpod#2373]
**Describe the bug**
Mocking away (AutoDispose)FamilyNotifier for widget tests breakes the tests on Flutter version 3.7.7. The same tests were running successfully on Flutter version 3.3.9.

Tested Flutter version where tests run successfully:
```
flutter --version
Flutter 3.3.9 • channel unknown • unknown source
Framework • revision b8f7f1f986 (4 months ago) • 2022-11-23 06:43:51 +0900
Engine • revision 8f2221fbef
Tools • Dart 2.18.5 • DevTools 2.15.0
```

Tested Flutter version where the same tests fail:
```
flutter --version
Flutter 3.7.7 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2ad6cd72c0 (2 weeks ago) • 2023-03-08 09:41:59 -0800
Engine • revision 1837b5be5f
Tools • Dart 2.19.4 • DevTools 2.20.1
```

Excerpt of the error message/stack trace:
```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building MyHomePage(dirty, dependencies:
[UncontrolledProviderScope], state: _ConsumerState#edb5d):
Class 'MockMyHomePageController' has no instance method '_setElement'.
Receiver: Instance of 'MockMyHomePageController'
Tried calling: _setElement(Instance of 'AutoDisposeNotifierProviderElement<MyHomePageController,
int>')

The relevant error-causing widget was:
  MyHomePage
  MyHomePage:file:///C:/private/example_family_notifier_provider_mock/test/widget_test.dart:31:15

When the exception was thrown, this was the stack:
#1      _ExternalProviderSubscription.read (package:riverpod/src/framework/provider_base.dart:177:29)
#2      ConsumerStatefulElement.watch (package:flutter_riverpod/src/consumer.dart:562:8)
#3      MyHomePage.build (package:example_family_notifier_provider_mock/src/my_home_page/my_home_page.dart:14:25)
#4      _ConsumerState.build (package:flutter_riverpod/src/consumer.dart:477:19)
#5      StatefulElement.build (package:flutter/src/widgets/framework.dart:5080:27)
#6      ConsumerStatefulElement.build (package:flutter_riverpod/src/consumer.dart:540:20)
#7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4968:15)
#8      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
```

**To Reproduce**
I created a small sample project for reproducing the behavior:
https://github.com/Chrisi63/flutterRiverpodFamilyNotifierMockExample

**Expected behavior**
I would expect mocking the (AutodDispose)FamilyNotifier to still be possible in the current stable Flutter version.

**Comment by rrousselGit** [comment]
Your mock is incorrectly defined

Don't `class ExampleMock extends Mock implements Example`

Do `class ExampleMock extends AutoDispose(Family)Notifier with Mock implements Example`

**Comment by Chrisi63** [comment]
Thanks a lot!

**Comment by 5hirish** [comment]
@rrousselGit we can't achieve the same with `mockito` code generation?

`@GenerateNiceMocks([
  MockSpec<Example>(),
])`
