### ISSUE TITLE
[riverpod_lint] - A lint plugin threw an exception dart(custom_lint_get_lint_fail)

### ISSUE THREAD

**Issue by VirtualAstronaut** [rrousselGit/riverpod#2689]
**Describe the bug**

I am getting "A lint plugin threw an exception dart(custom_lint_get_lint_fail)" with following code
"type 'DefaultFormalParameterImpl' is not a subtype of type 'SimpleFormalParameter' in type cast,"

**Edit**

It no longer throws error. I just removed `riverpod_lint` from `pubspec.yaml` and added again then relaunched vscode.

**To Reproduce**

```
import 'dart:io';
import 'package:riverpod_annotation/riverpod_annotation.dart';

@riverpod
Future<File> downloadFile({String? url}) async {
  return File('');
}
```

**Expected behaviour**

Linter should not throw Exception.

**Screenshot**

<img width="641" alt="Screenshot 2023-06-30 at 10 20 11 AM" src="https://github.com/rrousselGit/riverpod/assets/36418182/ef38a0e7-5554-4ac6-a740-9e68af3b0713">

**Log**

```
[stateless_ref] 2023-06-30T10:18:45.408768 Plugin stateless_ref threw while analyzing /Users/immence/Workspace/Flutter/immencers_mobile_v2/lib/core/file_utils.dart:
[stateless_ref] 2023-06-30T10:18:45.408768 type 'DefaultFormalParameterImpl' is not a subtype of type 'SimpleFormalParameter' in type cast
[stateless_ref] 2023-06-30T10:18:45.408768 #0      StatelessRef.run.<anonymous closure> (package:riverpod_lint/src/lints/stateless_ref.dart:43:15)
[stateless_ref] 2023-06-30T10:18:45.408768 #1      _RiverpodAstRegistryVisitor._runSubscriptions (package:riverpod_analyzer_utils/src/riverpod_ast/visitor.dart:958:12)
[stateless_ref] 2023-06-30T10:18:45.408768 #2      _RiverpodAstRegistryVisitor.visitStatelessProviderDeclaration (package:riverpod_analyzer_utils/src/riverpod_ast/visitor.dart:923:5)
[stateless_ref] 2023-06-30T10:18:45.408768 #3      StatelessProviderDeclaration.accept (package:riverpod_analyzer_utils/src/riverpod_ast/generator_provider_declaration.dart:321:13)
[stateless_ref] 2023-06-30T10:18:45.408768 #4      ResolvedRiverpodLibraryResult.visitChildren (package:riverpod_analyzer_utils/src/riverpod_ast/resolve_riverpod.dart:66:19)
[stateless_ref] 2023-06-30T10:18:45.408768 #5      _RiverpodAstRegistryVisitor.visitResolvedRiverpodUnit (package:riverpod_analyzer_utils/src/riverpod_ast/visitor.dart:870:12)
[stateless_ref] 2023-06-30T10:18:45.408768 #6      ResolvedRiverpodLibraryResult.accept (package:riverpod_analyzer_utils/src/riverpod_ast/resolve_riverpod.dart:53:13)
[stateless_ref] 2023-06-30T10:18:45.408768 #7      RiverpodAstRegistry.run (package:riverpod_analyzer_utils/src/riverpod_ast/visitor.dart:517:10)
[stateless_ref] 2023-06-30T10:18:45.408768 #8      _ParseRiverpod._setupRiverpod.<anonymous closure> (package:riverpod_lint/src/riverpod_custom_lint.dart:92:47)
[stateless_ref] 2023-06-30T10:18:45.408768 #9      _rootRun (dart:async/zone.dart:1399:13)
[stateless_ref] 2023-06-30T10:18:45.408768 #10     _CustomZone.run (dart:async/zone.dart:1301:19)
[stateless_ref] 2023-06-30T10:18:45.408768 #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1233:23)
[stateless_ref] 2023-06-30T10:18:45.408768 #12     runPostRunCallbacks (package:custom_lint_core/src/plugin_base.dart:16:19)
[stateless_ref] 2023-06-30T10:18:45.408768 #13     _ClientAnalyzerPlugin.analyzeFile.<anonymous closure> (package:custom_lint_builder/src/client.dart:812:7)
[stateless_ref] 2023-06-30T10:18:45.408768 <asynchronous suspension>
[stateless_ref] 2023-06-30T10:18:45.408768 #14     _ClientAnalyzerPlugin._runOperation (package:custom_lint_builder/src/client.dart:855:14)
[stateless_ref] 2023-06-30T10:18:45.408768 <asynchronous suspension>
[stateless_ref] 2023-06-30T10:18:45.408768 #15     _ClientAnalyzerPlugin.analyzeFile (package:custom_lint_builder/src/client.dart:776:5)
[stateless_ref] 2023-06-30T10:18:45.408768 <asynchronous suspension>
[stateless_ref] 2023-06-30T10:18:45.408768 #16     ServerPlugin.analyzeFiles (package:analyzer_plugin/plugin/plugin.dart:111:7)
[stateless_ref] 2023-06-30T10:18:45.408768 <asynchronous suspension>
[stateless_ref] 2023-06-30T10:18:45.408768 #17     ServerPlugin.handleAffectedFiles (package:analyzer_plugin/plugin/plugin.dart:211:5)
[stateless_ref] 2023-06-30T10:18:45.408768 <asynchronous suspension>
[stateless_ref] 2023-06-30T10:18:45.408768 #18     ServerPlugin.contentChanged.<anonymous closure> (package:analyzer_plugin/plugin/plugin.dart:141:9)
[stateless_ref] 2023-06-30T10:18:45.408768 <asynchronous suspension>
[stateless_ref] 2023-06-30T10:18:45.408768 #19     ServerPlugin._forAnalysisContexts (package:analyzer_plugin/plugin/plugin.dart:518:9)
[stateless_ref] 2023-06-30T10:18:45.408768 <asynchronous suspension>
[stateless_ref] 2023-06-30T10:18:45.408768 #20     ServerPlugin.contentChanged (package:analyzer_plugin/plugin/plugin.dart:136:7)
[stateless_ref] 2023-06-30T10:18:45.408768 <asynchronous suspension>
[stateless_ref] 2023-06-30T10:18:45.408768 #21     ServerPlugin.handleAnalysisUpdateContent (package:analyzer_plugin/plugin/plugin.dart:353:5)
[stateless_ref] 2023-06-30T10:18:45.408768 <asynchronous suspension>
[stateless_ref] 2023-06-30T10:18:45.408768 #22     ServerPlugin._getResponse (package:analyzer_plugin/plugin/plugin.dart:556:18)
[stateless_ref] 2023-06-30T10:18:45.408768 <asynchronous suspension>
[stateless_ref] 2023-06-30T10:18:45.408768 #23     ServerPlugin._onRequest (package:analyzer_plugin/plugin/plugin.dart:611:18)
[stateless_ref] 2023-06-30T10:18:45.408768 <asynchronous suspension>
[stateless_ref] 2023-06-30T10:18:45.408768
```

**Comment by rrousselGit** [comment]
Your provider is incorrectly written. Providers should always specify a ref:

```dart
@riverpod
Future<File> downloadFile(DownloadFileRef ref, {String? url}) async {
  return File('');
}
```

**Comment by rrousselGit** [comment]
I'll update the lint to not assume that ref is present
