### ISSUE TITLE
code generation error when future provider is deleted

### ISSUE THREAD

**Issue by sukwony** [rrousselGit/riverpod#2696]
**Describe the bug**
When I delete a future provider like below from source file, build_runner throws error
```
@riverpod
Future<String?> retrieveUrlFromClipboard(RetrieveUrlFromClipboardRef ref) async {
...
}
```
```
[WARNING] riverpod_generator on lib/ui/providers.dart:
An unexpected error was thrown trying to get location information on `AutoDisposeFutureProvider<String?> retrieveUrlFromClipboardProvider` (TopLevelVariableElementImpl).

Please file an issue at https://github.com/dart-lang/source_gen/issues/new
Include the contents of this warning and the stack trace along with
the version of `package:source_gen`, `package:analyzer` from `pubspec.lock`.

RangeError: Index: 0, Size: 0
[SEVERE] riverpod_generator on lib/ui/providers.dart:

Could not resolve annotation for `AutoDisposeFutureProvider<String?> retrieveUrlFromClipboardProvider`.
[WARNING] freezed on lib/ui/providers.dart:
An unexpected error was thrown trying to get location information on `AutoDisposeFutureProvider<String?> retrieveUrlFromClipboardProvider` (TopLevelVariableElementImpl).
```
```
["riverpod_generator on lib/ui/providers.dart",["","Could not resolve annotation for `AutoDisposeFutureProvider<String?> retrieveUrlFromClipboardProvider`.","#0      TypeChecker._computeConstantValue (package:source_gen/src/type_checker.dart:114:7)\n#1      TypeChecker._annotationsWhere (package:source_gen/src/type_checker.dart:139:21)\n#2      _SyncStarIterator.moveNext (dart:async-patch/async_patch.dart:554:14)\n#3      Iterable.isEmpty (dart:core/iterable.dart:537:33)\n#4      TypeChecker.firstAnnotationOfExact (package:source_gen/src/type_checker.dart:95:20)\n#5      LibraryReader.annotatedWithExact (package:source_gen/src/library.dart:67:34)\n#6      _SyncStarIterator.moveNext (dart:async-patch/async_patch.dart:554:14)\n#7      ParserGenerator.generate (package:riverpod_generator/src/parse_generator.dart:23:37)\n#8      _generate (package:source_gen/src/builder.dart:355:33)\n<asynchronous suspension>\n#9      Stream.toList.<anonymous closure> (dart:async/stream.dart:1343:9)\n<asynchronous suspension>\n"]]
```

```
["freezed on lib/ui/providers.dart",["","Could not resolve annotation for `AutoDisposeFutureProvider<String?> retrieveUrlFromClipboardProvider`.","#0      TypeChecker._computeConstantValue (package:source_gen/src/type_checker.dart:114:7)\n#1      TypeChecker._annotationsWhere (package:source_gen/src/type_checker.dart:139:21)\n#2      _SyncStarIterator.moveNext (dart:async-patch/async_patch.dart:554:14)\n#3      Iterable.isEmpty (dart:core/iterable.dart:537:33)\n#4      TypeChecker.firstAnnotationOf (package:source_gen/src/type_checker.dart:73:20)\n#5      TypeChecker.hasAnnotationOf (package:source_gen/src/type_checker.dart:80:7)\n#6      WhereIterator.moveNext (dart:_internal/iterable.dart:441:13)\n#7      ParserGenerator.generate (package:freezed/src/parse_generator.dart:29:37)\n<asynchronous suspension>\n#8      _generate (package:source_gen/src/builder.dart:355:23)\n<asynchronous suspension>\n#9      Stream.toList.<anonymous closure> (dart:async/stream.dart:1343:9)\n<asynchronous suspension>\n"]]
```

**To Reproduce**

1. write a future provider and complete code generation using build_runner watch
2. delete the future provider and save

pubspec.yaml

  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  freezed_annotation: ^2.2.0
  flutter_lints: ^2.0.0
  custom_lint: ^0.4.0
  riverpod_lint: ^1.3.1
  build_runner: ^2.3.3
  riverpod_generator: ^2.2.1
  freezed: ^2.3.3

**Expected behavior**
code generation succeeds without error

**Comment by rrousselGit** [comment]
This works for me. I've tried creating/generating/deleting a FutureProvider like you suggested, but faced no issue.

Make sure to run `dart pub upgrade`, just in case.

**Comment by rrousselGit** [comment]
I wonder if maybe the analysis was performed _before_ build_runner deleted the generated files? 🤔

**Comment by S-ecki** [comment]
I have faced the same issue once and solved it the following way, maybe that helps in finding the problem:
1. Delete `part` statement
2. Execute build_runner watch
3. Add the `part` statement again

When the build_runner finished after the third step, the build was successful and everything worked.

**Comment by rrousselGit** [comment]
It appears that this error isn't thrown by Riverpod but rather source_gen.

https://github.com/dart-lang/source_gen/issues/682
