### ISSUE TITLE
show error when reload data with overrides in ProviderScope 

### ISSUE THREAD

**Issue by phucdth12a** [rrousselGit/riverpod#2787]
In this example I have List<int> and show it. I have 3 button, button 'ADD'  to add new item, and button 'RELOAD' to reload List<int> to one item, and  button 'DELETE' to delete last item. I use overrides in ProviderScope, and it so great, it only build new item added. But when i press button 'RELOAD' or button 'DELETE' show this Error: 
```dart
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: RangeError (index): Invalid value: Only valid value is 0: 1
#0      List.[] (dart:core-patch/growable_array.dart:264:36)
#1      ItemWidget.build.<anonymous closure>
main.dart:139
#2      _ProviderSelector._select.<anonymous closure>
selector.dart:59
#3      ResultData.map
result.dart:60
#4      _ProviderSelector._select
selector.dart:58
#5      _ProviderSelector._selectOnChange
selector.dart:84
#6      _ProviderSelector.addListener.<anonymous closure>
selector.dart:120
#7      _RootZone.runBinaryGuarded (dart:async/zone.dart:1606:10)
#8      ProviderElementBase._notifyListeners.<anonymous closure>
element.dart:539
#9      ResultData.map
result.dart:60
#10     ProviderElementBase._notifyL<…>
```
I think cause when change length list item but length new list less than old list.

Code demo:
``` dart
void main() {
  runApp(
    ProviderScope(observers: [Logger()], child: const MyApp()),
  );
}

class Logger extends ProviderObserver {
  @override
  void didUpdateProvider(
    ProviderBase<Object?> provider,
    Object? previousValue,
    Object? newValue,
    ProviderContainer container,
  ) {
    print('''
{
  "provider": "${provider.name ?? provider.runtimeType}",
  "newValue": "$newValue"
}''');
  }
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const HomeDemo(),
    );
  }
}

class HomeDemo extends ConsumerWidget {
  const HomeDemo({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Scaffold(
      body: Column(
        children: [
          const SizedBox(
            height: 100,
          ),
          Row(
            children: [
              ElevatedButton(
                onPressed: () {
                  ref.read(todoProvider.notifier).addItem();
                },
                child: const Text('ADD'),
              ),
              ElevatedButton(
                onPressed: () {
                  Future.delayed(const Duration(seconds: 1), () {
                    ref.read(randomProvider.notifier).state =
                        Random().nextInt(10000);
                  });
                },
                child: const Text('RELOAD'),
              ),
              ElevatedButton(
                onPressed: () {
                  ref.read(todoProvider.notifier).deleteItem();
                },
                child: const Text('DELETE'),
              ),
            ],
          ),
          const SizedBox(height: 10),
          const Expanded(
            child: CustomScrollView(
              slivers: [
                ListView(),
                LoadingWidget(),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

class ListView extends ConsumerWidget {
  const ListView({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final length =
        ref.watch(todoProvider.select((value) => value.value?.length ?? 0));
    dev.log('length == $length');
    return SliverList(
      delegate: SliverChildBuilderDelegate(
        (BuildContext context, int index) {
          return Card(
            margin: const EdgeInsets.all(15),
            child: Container(
              height: 80,
              alignment: Alignment.center,
              child: Center(
                child: ProviderScope(
                  overrides: [indexProvider.overrideWithValue(index)],
                  child: const ItemWidget(),
                ),
              ),
            ),
          );
        },
        childCount: length, // 1000 list items
      ),
    );
  }
}

class ItemWidget extends ConsumerWidget {
  const ItemWidget({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final index = ref.read(indexProvider);
    dev.log('build index == $index');
    final int item =
        ref.watch(todoProvider.select((value) => value.value?[index] ?? 0));
    dev.log('build == $item');
    return Text(
      '$item',
      style: TextStyle(
          fontWeight: FontWeight.bold,
          fontSize: 20,
          color: Color((Random().nextDouble() * 0xFFFFFF).toInt())
              .withOpacity(1.0)),
    );
  }
}

class LoadingWidget extends ConsumerWidget {
  const LoadingWidget({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final isLoading = ref.watch(todoProvider).isLoading;
    return SliverToBoxAdapter(
      child: isLoading
          ? const Center(
              child: SizedBox(
                width: 30,
                height: 30,
                child: CircularProgressIndicator(),
              ),
            )
          : const SizedBox.shrink(),
    );
  }
}

final randomProvider = StateProvider((ref) => 1);

final todoProvider = AsyncNotifierProvider<TODO, List<int>>(() {
  return TODO();
});

class TODO extends AsyncNotifier<List<int>> {
  @override
  FutureOr<List<int>> build() async {
    final state = ref.watch(randomProvider);
    return [state];
  }

  addItem() async {
    state = const AsyncLoading();
    await Future.delayed(const Duration(seconds: 1));
    state = AsyncData([...state.value ?? [], Random().nextInt(10)]);
  }

  deleteItem() {
    final data = (state.value ?? []);
    data.removeLast();
    state = AsyncData(data);
  }
}

final indexProvider = Provider<int>((_) {
  throw UnimplementedError();
});


```

**Comment by rrousselGit** [comment]
Please format your code and use code blocks:

````
```dart
your code
```
````

**Comment by phucdth12a** [comment]
Yes. i have changed my code. Tks.

**Comment by rrousselGit** [comment]
Doing:

```dart
.select((value) => value.value?[index] ?? 0)
```

is technically unsafe. If the list size diminish, `index` may be greater than the list length, which will throw.

You could use `list.elementAtOrNull(index)` from `package:collection`
