### ISSUE TITLE
[riverpod_lint] Bad state: Unknown provider type BlocProvider

### ISSUE THREAD

**Issue by shilangyu** [rrousselGit/riverpod#2911]
**Describe the bug**

`riverpod_lint` crashes with the following log when using `package:riverbloc`:

```txt
➜ dart run custom_lint
Building package executable... (3.0s)
Built custom_lint:custom_lint.
Plugin functional_ref threw while analyzing /Users/x/coding/temp/riverpod_lint_unknown_provider/lib/riverpod_lint_unknown_provider.dart:
Bad state: Unknown provider type BlocProvider<C, int>
#0      LegacyProviderType._parse (package:riverpod_analyzer_utils/src/riverpod_element.dart:180:5)
#1      LegacyProviderDeclarationElement.parse.<anonymous closure> (package:riverpod_analyzer_utils/src/riverpod_element.dart:213:43)
#2      _extension#0.putIfAbsent (package:riverpod_analyzer_utils/src/riverpod_element.dart:382:42)
#3      LegacyProviderDeclarationElement.parse (package:riverpod_analyzer_utils/src/riverpod_element.dart:197:19)
#4      LegacyProviderDeclaration._parse (package:riverpod_analyzer_utils/src/riverpod_ast/legacy_provider_declaration.dart:105:62)
#5      _ParseRiverpodUnitVisitor.visitVariableDeclaration (package:riverpod_analyzer_utils/src/riverpod_ast/resolve_riverpod.dart:240:51)
#6      VariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:18757:50)
#7      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:12998:20)
#8      VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:18900:16)
#9      RecursiveAstVisitor.visitVariableDeclarationList (package:analyzer/dart/ast/visitor.dart:1780:10)
#10     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:18894:15)
#11     TopLevelVariableDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:17963:19)
#12     RecursiveAstVisitor.visitTopLevelVariableDeclaration (package:analyzer/dart/ast/visitor.dart:1738:10)
#13     TopLevelVariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:17958:15)
#14     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:12998:20)
#15     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3631:21)
#16     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:942:10)
#17     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:3624:50)
#18     new ResolvedRiverpodLibraryResult.from (package:riverpod_analyzer_utils/src/riverpod_ast/resolve_riverpod.dart:16:14)
#19     _ParseRiverpod._setupRiverpod (package:riverpod_lint/src/riverpod_custom_lint.dart:90:50)
<asynchronous suspension>
#20     RiverpodLintRule.startUp (package:riverpod_lint/src/riverpod_custom_lint.dart:62:5)
<asynchronous suspension>

The request analysis.setContextRoots failed with the following error:
RequestErrorCode.PLUGIN_ERROR
A request throw the exception:Bad state: Unknown provider type BlocProvider<C, int>
#0      LegacyProviderType._parse (package:riverpod_analyzer_utils/src/riverpod_element.dart:180:5)
#1      LegacyProviderDeclarationElement.parse.<anonymous closure> (package:riverpod_analyzer_utils/src/riverpod_element.dart:213:43)
#2      _extension#0.putIfAbsent (package:riverpod_analyzer_utils/src/riverpod_element.dart:382:42)
#3      LegacyProviderDeclarationElement.parse (package:riverpod_analyzer_utils/src/riverpod_element.dart:197:19)
#4      LegacyProviderDeclaration._parse (package:riverpod_analyzer_utils/src/riverpod_ast/legacy_provider_declaration.dart:105:62)
#5      _ParseRiverpodUnitVisitor.visitVariableDeclaration (package:riverpod_analyzer_utils/src/riverpod_ast/resolve_riverpod.dart:240:51)
#6      VariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:18757:50)
#7      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:12998:20)
#8      VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:18900:16)
#9      RecursiveAstVisitor.visitVariableDeclarationList (package:analyzer/dart/ast/visitor.dart:1780:10)
#10     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:18894:15)
#11     TopLevelVariableDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:17963:19)
#12     RecursiveAstVisitor.visitTopLevelVariableDeclaration (package:analyzer/dart/ast/visitor.dart:1738:10)
#13     TopLevelVariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:17958:15)
#14     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:12998:20)
#15     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3631:21)
#16     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:942:10)
#17     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:3624:50)
#18     new ResolvedRiverpodLibraryResult.from (package:riverpod_analyzer_utils/src/riverpod_ast/resolve_riverpod.dart:16:14)
#19     _ParseRiverpod._setupRiverpod (package:riverpod_lint/src/riverpod_custom_lint.dart:90:50)
<asynchronous suspension>
#20     RiverpodLintRule.startUp (package:riverpod_lint/src/riverpod_custom_lint.dart:62:5)
<asynchronous suspension>

at:
#0      SocketCustomLintServerToClientChannel.sendCustomLintRequest.<anonymous closure> (package:custom_lint/src/v2/server_to_client_channel.dart:275:11)
#1      _$_CustomLintResponseAnalyzerPluginResponse.map (package:custom_lint/src/v2/protocol.freezed.dart:924:34)
#2      SocketCustomLintServerToClientChannel.sendCustomLintRequest (package:custom_lint/src/v2/server_to_client_channel.dart:269:14)
<asynchronous suspension>
#3      SocketCustomLintServerToClientChannel.sendAnalyzerPluginRequest (package:custom_lint/src/v2/server_to_client_channel.dart:246:22)
<asynchronous suspension>
#4      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)
<asynchronous suspension>
#5      SocketCustomLintServerToClientChannel.init (package:custom_lint/src/v2/server_to_client_channel.dart:141:5)
<asynchronous suspension>
#6      CustomLintServer._maybeSpawnCustomLintPlugin (package:custom_lint/src/v2/custom_lint_analyzer_plugin.dart:364:5)
<asynchronous suspension>
#7      CustomLintServer._handleAnalysisSetContextRoots.<anonymous closure> (package:custom_lint/src/v2/custom_lint_analyzer_plugin.dart:328:9)
<asynchronous suspension>
#8      PendingOperation.run (package:custom_lint/src/async_operation.dart:22:14)
<asynchronous suspension>
#9      CustomLintServer._handleRequest (package:custom_lint/src/v2/custom_lint_analyzer_plugin.dart:160:22)
<asynchronous suspension>

_PrettyRequestFailure: {"code":"PLUGIN_ERROR","message":"A request throw the exception:Bad state: Unknown provider type BlocProvider<C, int>\n#0      LegacyProviderType._parse (package:riverpod_analyzer_utils/src/riverpod_element.dart:180:5)\n#1      LegacyProviderDeclarationElement.parse.<anonymous closure> (package:riverpod_analyzer_utils/src/riverpod_element.dart:213:43)\n#2      _extension#0.putIfAbsent (package:riverpod_analyzer_utils/src/riverpod_element.dart:382:42)\n#3      LegacyProviderDeclarationElement.parse (package:riverpod_analyzer_utils/src/riverpod_element.dart:197:19)\n#4      LegacyProviderDeclaration._parse (package:riverpod_analyzer_utils/src/riverpod_ast/legacy_provider_declaration.dart:105:62)\n#5      _ParseRiverpodUnitVisitor.visitVariableDeclaration (package:riverpod_analyzer_utils/src/riverpod_ast/resolve_riverpod.dart:240:51)\n#6      VariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:18757:50)\n#7      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:12998:20)\n#8      VariableDeclarationListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:18900:16)\n#9      RecursiveAstVisitor.visitVariableDeclarationList (package:analyzer/dart/ast/visitor.dart:1780:10)\n#10     VariableDeclarationListImpl.accept (package:analyzer/src/dart/ast/ast.dart:18894:15)\n#11     TopLevelVariableDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:17963:19)\n#12     RecursiveAstVisitor.visitTopLevelVariableDeclaration (package:analyzer/dart/ast/visitor.dart:1738:10)\n#13     TopLevelVariableDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:17958:15)\n#14     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:12998:20)\n#15     CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:3631:21)\n#16     RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:942:10)\n#17     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:3624:50)\n#18     new ResolvedRiverpodLibraryResult.from (package:riverpod_analyzer_utils/src/riverpod_ast/resolve_riverpod.dart:16:14)\n#19     _ParseRiverpod._setupRiverpod (package:riverpod_lint/src/riverpod_custom_lint.dart:90:50)\n<asynchronous suspension>\n#20     RiverpodLintRule.startUp (package:riverpod_lint/src/riverpod_custom_lint.dart:62:5)\n<asynchronous suspension>\n","stackTrace":"#0      SocketCustomLintServerToClientChannel.sendCustomLintRequest.<anonymous closure> (package:custom_lint/src/v2/server_to_client_channel.dart:275:11)\n#1      _$_CustomLintResponseAnalyzerPluginResponse.map (package:custom_lint/src/v2/protocol.freezed.dart:924:34)\n#2      SocketCustomLintServerToClientChannel.sendCustomLintRequest (package:custom_lint/src/v2/server_to_client_channel.dart:269:14)\n<asynchronous suspension>\n#3      SocketCustomLintServerToClientChannel.sendAnalyzerPluginRequest (package:custom_lint/src/v2/server_to_client_channel.dart:246:22)\n<asynchronous suspension>\n#4      Future.wait.<anonymous closure> (dart:async/future.dart:525:21)\n<asynchronous suspension>\n#5      SocketCustomLintServerToClientChannel.init (package:custom_lint/src/v2/server_to_client_channel.dart:141:5)\n<asynchronous suspension>\n#6      CustomLintServer._maybeSpawnCustomLintPlugin (package:custom_lint/src/v2/custom_lint_analyzer_plugin.dart:364:5)\n<asynchronous suspension>\n#7      CustomLintServer._handleAnalysisSetContextRoots.<anonymous closure> (package:custom_lint/src/v2/custom_lint_analyzer_plugin.dart:328:9)\n<asynchronous suspension>\n#8      PendingOperation.run (package:custom_lint/src/async_operation.dart:22:14)\n<asynchronous suspension>\n#9      CustomLintServer._handleRequest (package:custom_lint/src/v2/custom_lint_analyzer_plugin.dart:160:22)\n<asynchronous suspension>\n"}
#0      ChannelBase.sendRequest (package:custom_lint/src/server_isolate_channel.dart:82:7)
<asynchronous suspension>
#1      CustomLintRunner.initialize.<anonymous closure> (package:custom_lint/src/runner.dart:51:5)
<asynchronous suspension>
#2      _runServer.<anonymous closure> (package:custom_lint/custom_lint.dart:89:7)
<asynchronous suspension>
```

I would imagine the same crash would happen if I were to use any other custom provider.

**To Reproduce**

See prepared minimal repo that reproduces this issue: https://github.com/shilangyu/riverpod_lint_unknown_provider

**Expected behavior**
No crash, external providers should be accepted.

**Comment by rrousselGit** [comment]
Custom providers never were supported.

**Comment by shilangyu** [comment]
Are you saying that riverpod itself doesn't support creation of custom providers?

**Comment by MiniSuperDev** [comment]
Hi @rrousselGit
What would be the correct way to ensure that blocs/cubit can be used in a similar way to notifiers since riverbloc use internal files of riverpod?
Thanks
