### ISSUE TITLE
[lint] A lint plugin threw an exceptiondart(custom_lint_get_lint_fail)

### ISSUE THREAD

**Issue by NeroThroN** [rrousselGit/riverpod#2967]
**Describe the bug:**
In a file where I have multiples provider defined (that used `riverpod_generator`) that do not imply `BuildContext`, on the first line I have the following error:
```
A lint plugin threw an exceptiondart(custom_lint_get_lint_fail)
```

___

**Log file:**
<details>
<summary>custom_lint.log</summary>

```
[avoid_build_context_in_providers] 2023-10-09T10:29:32.332295 Plugin avoid_build_context_in_providers threw while analyzing /home/nerothron/[...]/lib/providers/position.provider.dart:
[avoid_build_context_in_providers] 2023-10-09T10:29:32.332295 Null check operator used on a null value
[avoid_build_context_in_providers] 2023-10-09T10:29:32.332295 #0      AvoidBuildContextInProviders.run.<anonymous closure> (package:riverpod_lint/src/lints/avoid_build_context_in_providers.dart:38:45)
[avoid_build_context_in_providers] 2023-10-09T10:29:32.332295 #1      _RiverpodAstRegistryVisitor._runSubscriptions (package:riverpod_analyzer_utils/src/riverpod_ast/visitor.dart:961:12)
[avoid_build_context_in_providers] 2023-10-09T10:29:32.332295 #2      _RiverpodAstRegistryVisitor.visitClassBasedProviderDeclaration (package:riverpod_analyzer_utils/src/riverpod_ast/visitor.dart:915:5)
[avoid_build_context_in_providers] 2023-10-09T10:29:32.332295 #3      ClassBasedProviderDeclaration.accept (package:riverpod_analyzer_utils/src/riverpod_ast/generator_provider_declaration.dart:258:13)
[avoid_build_context_in_providers] 2023-10-09T10:29:32.332295 #4      ResolvedRiverpodLibraryResult.visitChildren (package:riverpod_analyzer_utils/src/riverpod_ast/resolve_riverpod.dart:69:19)
[avoid_build_context_in_providers] 2023-10-09T10:29:32.332295 #5      _RiverpodAstRegistryVisitor.visitResolvedRiverpodUnit (package:riverpod_analyzer_utils/src/riverpod_ast/visitor.dart:870:12)
[avoid_build_context_in_providers] 2023-10-09T10:29:32.332295 #6      ResolvedRiverpodLibraryResult.accept (package:riverpod_analyzer_utils/src/riverpod_ast/resolve_riverpod.dart:53:13)
[avoid_build_context_in_providers] 2023-10-09T10:29:32.332295 #7      RiverpodAstRegistry.run (package:riverpod_analyzer_utils/src/riverpod_ast/visitor.dart:517:10)
[avoid_build_context_in_providers] 2023-10-09T10:29:32.332295 #8      _ParseRiverpod._setupRiverpod.<anonymous closure> (package:riverpod_lint/src/riverpod_custom_lint.dart:92:47)
[avoid_build_context_in_providers] 2023-10-09T10:29:32.332295 #9      _rootRun (dart:async/zone.dart:1399:13)
[avoid_build_context_in_providers] 2023-10-09T10:29:32.332295 #10     _CustomZone.run (dart:async/zone.dart:1301:19)
[avoid_build_context_in_providers] 2023-10-09T10:29:32.332295 #11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1233:23)
[avoid_build_context_in_providers] 2023-10-09T10:29:32.332295 #12     runPostRunCallbacks (package:custom_lint_core/src/plugin_base.dart:16:19)
[avoid_build_context_in_providers] 2023-10-09T10:29:32.332295 #13     _ClientAnalyzerPlugin.analyzeFile.<anonymous closure> (package:custom_lint_builder/src/client.dart:812:7)
[avoid_build_context_in_providers] 2023-10-09T10:29:32.332295 <asynchronous suspension>
[avoid_build_context_in_providers] 2023-10-09T10:29:32.332295 #14     _ClientAnalyzerPlugin._runOperation (package:custom_lint_builder/src/client.dart:855:14)
[avoid_build_context_in_providers] 2023-10-09T10:29:32.332295 <asynchronous suspension>
[avoid_build_context_in_providers] 2023-10-09T10:29:32.332295 #15     _ClientAnalyzerPlugin.analyzeFile (package:custom_lint_builder/src/client.dart:776:5)
[avoid_build_context_in_providers] 2023-10-09T10:29:32.332295 <asynchronous suspension>
[avoid_build_context_in_providers] 2023-10-09T10:29:32.332295 #16     ServerPlugin.analyzeFiles (package:analyzer_plugin/plugin/plugin.dart:111:7)
[avoid_build_context_in_providers] 2023-10-09T10:29:32.332295 <asynchronous suspension>
[avoid_build_context_in_providers] 2023-10-09T10:29:32.332295 #17     ServerPlugin.handleAffectedFiles (package:analyzer_plugin/plugin/plugin.dart:211:5)
[avoid_build_context_in_providers] 2023-10-09T10:29:32.332295 <asynchronous suspension>
[avoid_build_context_in_providers] 2023-10-09T10:29:32.332295 #18     ServerPlugin.contentChanged.<anonymous closure> (package:analyzer_plugin/plugin/plugin.dart:141:9)
[avoid_build_context_in_providers] 2023-10-09T10:29:32.332295 <asynchronous suspension>
[avoid_build_context_in_providers] 2023-10-09T10:29:32.332295 #19     ServerPlugin._forAnalysisContexts (package:analyzer_plugin/plugin/plugin.dart:510:9)
[avoid_build_context_in_providers] 2023-10-09T10:29:32.332295 <asynchronous suspension>
[avoid_build_context_in_providers] 2023-10-09T10:29:32.332295 #20     ServerPlugin.contentChanged (package:analyzer_plugin/plugin/plugin.dart:136:7)
[avoid_build_context_in_providers] 2023-10-09T10:29:32.332295 <asynchronous suspension>
[avoid_build_context_in_providers] 2023-10-09T10:29:32.332295 #21     ServerPlugin.handleAnalysisUpdateContent (package:analyzer_plugin/plugin/plugin.dart:353:5)
[avoid_build_context_in_providers] 2023-10-09T10:29:32.332295 <asynchronous suspension>
[avoid_build_context_in_providers] 2023-10-09T10:29:32.332295 #22     ServerPlugin._getResponse (package:analyzer_plugin/plugin/plugin.dart:548:18)
[avoid_build_context_in_providers] 2023-10-09T10:29:32.332295 <asynchronous suspension>
[avoid_build_context_in_providers] 2023-10-09T10:29:32.332295 #23     ServerPlugin._onRequest (package:analyzer_plugin/plugin/plugin.dart:599:18)
[avoid_build_context_in_providers] 2023-10-09T10:29:32.332295 <asynchronous suspension>
[avoid_build_context_in_providers] 2023-10-09T10:29:32.332295
```

</details>

**Code throwing error:**
<details>
<summary>avoid_build_context_in_providers.dart</summary>

```dart
@override
void run(
  CustomLintResolver resolver,
  ErrorReporter reporter,
  CustomLintContext context,
) {
  riverpodRegistry(context).addFunctionalProviderDeclaration((declaration) {
    final parameters = declaration.node.functionExpression.parameters!;
    _emitWarningsForBuildContext(reporter, parameters);
  });

  riverpodRegistry(context).addClassBasedProviderDeclaration((declaration) {
    final methods = declaration.node.members.whereType<MethodDeclaration>();

    for (final method in methods) {
      final parameters = method.parameters!; // <== Null check operator used on a null value here
      _emitWarningsForBuildContext(reporter, parameters);
    }
  });
}
```

</details>

**Comment by NeroThroN** [comment]
Seems to be a duplicate of #2959 
With a pending PR #2964
