### ISSUE TITLE
Unable to test provider with async  dart:io

### ISSUE THREAD

**Issue by woprandi** [rrousselGit/riverpod#3033]
I'm unable to test provider with async IO code inside, despite `WidgetTester.runAsync()` 

```dart
@riverpod
Future<String> basic(BasicRef ref, String path) async {
  return await File(path).readAsString();
}
```

```dart
class MyHomePage extends ConsumerWidget {
  final String path;
  const MyHomePage({super.key, required this.path});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    //final value = ref.watch(myNotifierProvider(path));
    final value = ref.watch(basicProvider(path));

    print(value);
    return Scaffold(
      body: Text(value.valueOrNull ?? ''),
    );
  }
}
```

```dart
  testWidgets('test', (tester) async {
    await tester.runAsync(() async {
      await tester.pumpWidget(
        const ProviderScope(
          child: MaterialApp(
            home: MyHomePage(
              path: 'test/file.txt',
            ),
          ),
        ),
      );
      await tester.pump();
      await tester.pump();
      expect(find.text('test'), findsOneWidget);
    });
  });
```

```
AsyncLoading<String>()
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown while running async test code:
Expected: exactly one matching node in the widget tree
  Actual: _TextFinder:<zero widgets with text "test" (ignoring offstage widgets)>
   Which: means none were found but one was expected

When the exception was thrown, this was the stack:
#0      fail (package:matcher/src/expect/expect.dart:149:31)
#1      _expect (package:matcher/src/expect/expect.dart:144:3)
#2      expect (package:matcher/src/expect/expect.dart:56:3)
#3      expect (package:flutter_test/src/widget_tester.dart:454:18)
#4      main.<anonymous closure>.<anonymous closure> (file:///home/william/Documents/Repos/testapp/test/widget_test.dart:34:7)
<asynchronous suspension>

The exception was caught asynchronously.
════════════════════════════════════════════════════════════════════════════════════════════════════
```

It works without problem with sync IO

**Comment by woprandi** [comment]
The example seems suitable for unit test when we test providers directly.
On widget tests we generally don't have a `ProviderContainer` instance and we just want to wait providers to be completed
However I wrote that.

```dart
  testWidgets('test', (tester) async {
    await tester.runAsync(() async {
      final container = ProviderContainer();
      await tester.pumpWidget(
        UncontrolledProviderScope(
          container: container,
          child: const MaterialApp(
            home: MyHomePage(
              path: 'test/file.txt',
            ),
          ),
        ),
      );

      await container.read(basicProvider('test/file.txt').future);
      await tester.pump();
      expect(find.text('test'), findsOneWidget);
    });
  });
```

Which passes. But I think it's little cumbersome

**Comment by rrousselGit** [comment]
It is already explained in the docs how to obtain the ProviderContainer instance. And this doesn't need UncontrolledProviderScope
