### ISSUE TITLE
AsyncNotifier inside element must be a class?

### ISSUE THREAD

**Issue by getong** [rrousselGit/riverpod#3044]
code:
```
import 'package:flutter/material.dart';
import 'dart:async';
import 'package:flutter_riverpod/flutter_riverpod.dart';

final counterProvider =
    AsyncNotifierProvider<CounterNotifier, int>(() => CounterNotifier());

class CounterNotifier extends AsyncNotifier<int> {
  late int num;

  CounterNotifier() {
    _initializeCounter();
  }

  @override
  FutureOr<int> build() async {
    return num;
  }

  Future<void> _initializeCounter() async {
    num = 0;
    state = AsyncData(num);
  }

  Future<void> refreshCounter() async {
    state = AsyncValue.data(num++);

    ref.refresh(counterProvider);
  }
}

void main() {
  runApp(ProviderScope(
      child: MaterialApp(
    home: MyApp(),
  )));
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Async Counter Example'),
      ),
      body: Center(
        child: Consumer(
          builder: (context, ref, child) {
            final asyncValue = ref.watch(counterProvider);
            return asyncValue.when(
                loading: () => CircularProgressIndicator(),
                error: (error, stackTrace) => Text('Error: $error'),
                data: (counter) {
                  return Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: <Widget>[
                      Text('Counter Value: $counter'),
                      ElevatedButton(
                        onPressed: () {
                          ref.read(counterProvider.notifier).refreshCounter();
                        },
                        child: Text('Refresh Counter'),
                      ),
                    ],
                  );
                });
          },
        ),
      ),
    );
  }
}

```

the error begin:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LateInitializationError: Field '_element@20502701' has not been initialized.
#0      BuildlessAsyncNotifier._element (package:riverpod/src/async_notifier/base.dart)
#1      AsyncNotifierBase.state= (package:riverpod/src/async_notifier.dart:56:5)
#2      CounterNotifier._initializeCounter (package:flutter_riverpod_invalidate_example/main.dart:22:5)
#3      new CounterNotifier (package:flutter_riverpod_invalidate_example/main.dart:12:5)
#4      counterProvider.<anonymous closure> (package:flutter_riverpod_invalidate_example/main.dart:6:55)
#5      AsyncNotifierProviderElement.create.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:519:38)
```

I finally found that 
```
AsyncNotifierProvider<CounterNotifier, int>(() => CounterNotifier());
```
If I create a new class, which is not `int`, the code works.
I wonder that, the element inside AsyncNotifier must be a class? Or I miss something?
Thanks for your time.

**Comment by rrousselGit** [comment]
You're not allowed to perform logic inside the constructor of Notifiers.

Have your _initializeCounter in the `build` method instead

**Comment by getong** [comment]
Thanks.
