### ISSUE TITLE
Code broken bewteen version 2.4.8 and 2.4.9

### ISSUE THREAD

**Issue by sgruhier** [rrousselGit/riverpod#3296]
**Describe the bug**
Breaking since 2.4.9 before it was working fine.
The error is `CircularDependencyError`

```
flutter: Instance of 'CircularDependencyError'
flutter: 
#0      ProviderElementBase._debugAssertCanDependOn.<anonymous closure> (package:riverpod/src/framework/element.dart:661:13)
#1      ProviderElementBase._debugAssertCanDependOn (package:riverpod/src/framework/element.dart:666:8)
#2      ProviderElementBase.invalidate (package:riverpod/src/framework/element.dart:290:12)
#3      SettingsController.updateSetting (package:cp_mobile_app/shared/architecture/providers/settings_controller.dart:22:9)
``` 

when I call `ref.invalidate(getSettingsProvider);` 
May be I'm doing it wrong. 

**To Reproduce**

Here is a snippet of the code. I guess easy to understand.
When I call `updateSetting` I invalidate `getSettingsProvider` to force a reload.

```dart
class SettingsController {
  SettingsController(this.ref, this.repository);
  final SettingsRepository repository;
  final Ref ref;

  Future<AppGlobalSettings> getSettings() {
    return repository.getSettings();
  }

  Future<bool> updateSetting(AppGlobalSetting setting) async {
    final response = await repository.updateSetting(setting);
    ref.invalidate(getSettingsProvider);
    return response;
  }
}

final _settingsRepositoryProvider = Provider<SettingsRepository>((ref) {
  final storageService = ref.watch(storageServiceProvider);
  return FakeSettingsRepository(storageService);
});

final settingsControllerProvider = Provider<SettingsController>((ref) {
  final repository = ref.watch(_settingsRepositoryProvider);
  return SettingsController(ref, repository);
});

final getSettingsProvider = FutureProvider<AppGlobalSettings>((ref) async {
  final settingsController = ref.watch(settingsControllerProvider);
  return settingsController.getSettings();
});
```

**Comment by sgruhier** [comment]
I read a bit element.dart, in fact before 2.4.9, there wasn't an assert, now there is 
`    assert(_debugAssertCanDependOn(provider), ''); `

**Comment by rrousselGit** [comment]
It's not broken now. It was broken before.

The code always should've thrown, but incorrectly didn't. The bug was fixed and it now correctly throws.

**Comment by sgruhier** [comment]
Thanks for that quick answer! You rock.

That's what I thought even if my app was working well :)
invalidate a FutureProvider is a bad behavior?

**Comment by rrousselGit** [comment]
No, it's about how you have a circular dependency. This isn't allowed
